"""Restored trees retain internal objects and never execute foreign donor tools."""
import io
import json
import os
from pathlib import Path
import struct
import tempfile
import unittest
from contextlib import ExitStack, redirect_stdout
from unittest import mock

from tools import prepare_restored_build as prepare
from tools import restore_upstream_cache as restore


class PrepareRestoredBuildTest(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.work = Path(self.temporary.name)
        self.src = self.work / "src"
        self.out = self.src / "out/Default"
        (self.out / "obj").mkdir(parents=True)
        (self.src / "include").mkdir()
        (self.src / "include/a.h").write_text("header")

    def write(self, path, content):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content.encode() if isinstance(content, str) else content)
        return path

    def object(self, name):
        return self.write(self.out / "obj" / name, "object")

    def binary(self, path, platform, arch):
        header = bytearray(64)
        if platform == "macos":
            header[:4] = b"\xcf\xfa\xed\xfe"
            struct.pack_into("<I", header, 4, {"x64": 0x1000007, "arm64": 0x100000C}[arch])
        elif platform == "linux":
            header[:6] = b"\x7fELF\x02\x01"
            struct.pack_into("<H", header, 18, {"x64": 62, "arm64": 183}[arch])
        else:
            header[:2] = b"MZ"
            struct.pack_into("<I", header, 60, 64)
            header.extend(b"PE\0\0" + struct.pack("<H", 0x8664))
        self.write(path, header)
        path.chmod(0o755)

    def fixture(self, platform="macos", arch="arm64", donor_arch=None, *, host_arch=None):
        identity, _, manifest = restore.identities(prepare.ROOT, platform, arch)
        version = "\n".join(f"{key}={value}" for key, value in zip(
            ("MAJOR", "MINOR", "BUILD", "PATCH"), identity["chromium_version"].split(".")))
        self.write(self.src / "chrome/VERSION", version)
        self.write(self.src / "BUILD.gn", "# source")
        self.write(self.out / "args.gn", f'target_cpu = "{arch}"\n')
        self.write(self.out / "build.ninja", "# regenerated by the native builder")
        self.write(self.out / ".ninja_log", "# ninja log v5\n")
        self.write(self.out / ".ninja_deps", b"# ninjadeps\n\x04\0\0\0")
        receipt = {"schema_version": 1, "owner": restore.OWNER, "status": "restored",
                   "extraction_scope": restore.fetcher.SOURCE_SCOPE, "identity": identity,
                   "manifest": manifest, "platform": platform, "arch": arch,
                   "original_args": restore.source_args(self.src, identity), "external_symlink_paths": []}
        self.write(self.src / restore.MARKER, json.dumps(receipt))
        for relative in prepare.tool_paths(platform, arch, host_arch=host_arch).values():
            self.binary(self.src / relative, platform, donor_arch or host_arch or arch)
        # Upstream macOS resources have nested nightly components and no Chromium stamps.
        if platform == "macos":
            rust = self.src / prepare.RUST
            for name in ("rustc", "cargo"):
                path = rust / "bin" / name
                destination = rust / name / "bin" / name
                destination.parent.mkdir(parents=True)
                path.rename(destination)
                path.symlink_to(Path("..") / name / "bin" / name)
            self.write(rust / "version", "1.91.0-nightly (2026-06-16)")
        return receipt

    def deps(self, records):
        paths = list(dict.fromkeys(name for output, inputs in records.items() for name in (output, *inputs)))
        data = bytearray(b"# ninjadeps\n\x04\0\0\0")
        for index, name in enumerate(paths):
            payload = name.encode()
            payload += b"\0" * (-len(payload) % 4)
            payload += struct.pack("<I", ~index & 0xffffffff)
            data += struct.pack("<I", len(payload)) + payload
        for output, inputs in records.items():
            values = [paths.index(output), 1, 0] + [paths.index(name) for name in inputs]
            payload = struct.pack(f"<{len(values)}I", *values)
            data += struct.pack("<I", 0x80000000 | len(payload)) + payload
        self.write(self.out / ".ninja_deps", data)

    def native_context(self, platform="macos", arch="arm64"):
        stack = ExitStack()
        stack.enter_context(mock.patch.object(prepare, "host_identity", return_value=(platform, arch)))
        stack.enter_context(mock.patch.object(prepare.subprocess, "run", return_value=mock.Mock(
            returncode=0, stdout="thirdparty LLVM 23 / rustc nightly")))
        stack.enter_context(mock.patch.object(prepare, "environment_identity", return_value={"ImageOS": "macos15", "ImageVersion": "1", "SDK": "/sdk/26"}))
        return stack

    def test_internal_dependencies_keep_object_and_mtime(self):
        output = self.object("a.o")
        before = output.stat().st_mtime_ns
        self.deps({"obj/a.o": ["../../include/a.h"]})
        result = prepare.invalidate_external_dependencies(self.src)
        self.assertEqual(result["removed_outputs"], 0)
        self.assertEqual(output.stat().st_mtime_ns, before)

    def test_external_and_missing_dependencies_rebuild_only_affected_outputs(self):
        for name in ("a.o", "b.o", "c.obj", "d.o", "e.o"):
            self.object(name)
        self.deps({"obj/a.o": ["../../include/a.h"], "obj/b.o": ["/Applications/Xcode.app/SDK/stdlib.h"],
                   "obj\\c.obj": ["C:\\Program Files\\SDK\\stddef.h"], "obj/d.o": ["../../../external.h"],
                   "obj/e.o": ["../../include/missing.h"]})
        result = prepare.invalidate_external_dependencies(self.src)
        self.assertEqual(result["external_dependency_outputs"], 3)
        self.assertEqual(result["missing_dependency_outputs"], 1)
        self.assertEqual(result["removed_outputs"], 4)
        self.assertEqual([path.name for path in (self.out / "obj").iterdir()], ["a.o"])

    def test_unknown_external_dependency_invalidates_every_reader(self):
        for name in ("a.o", "b.o", "c.o"):
            self.object(name)
        self.deps({"obj/a.o": ["/unknown/header"], "obj/b.o": ["/unknown/header"], "obj/c.o": ["../../include/a.h"]})
        result = prepare.invalidate_external_dependencies(self.src)
        self.assertEqual(result["removed_outputs"], 2)
        self.assertTrue((self.out / "obj/c.o").exists())

    def test_external_dependency_invalidates_nested_sdk_object(self):
        name = "obj/third_party/webrtc/sdk/helpers_objc/NSString+StdString.o"
        output = self.write(self.out / name, "object")
        for root in (self.out, self.src):
            for value in (output.relative_to(root).as_posix(), str(output.relative_to(root)).replace("/", "\\")):
                with self.subTest(root=root, value=value):
                    self.assertEqual(prepare.inside_path(root, value, output=True), output)
        self.deps({name: ["/external-sdk/header.h"]})
        result = prepare.invalidate_external_dependencies(self.src)
        self.assertEqual(result["external_dependency_outputs"], 1)
        self.assertEqual(result["removed_outputs"], 1)
        self.assertEqual(result["unknown_outputs"], [])
        self.assertFalse(output.exists())

    def test_generated_output_in_nested_devtools_sdk_is_invalidated(self):
        name = "gen/third_party/devtools-frontend/src/front_end/core/sdk/sdk.js"
        output = self.write(self.out / name, "generated")
        self.deps({})
        self.write(self.out / ".ninja_log", f"# ninja log v5\n0\t1\t1\t{name}\tabc\n")
        result = prepare.invalidate_generated_outputs(self.src)
        self.assertEqual(result, {"removed_outputs": 1, "unknown_outputs": []})
        self.assertFalse(output.exists())

    def test_compiled_walk_includes_nested_sdk_outputs(self):
        outputs = [self.object(name) for name in (
            "third_party/webrtc/sdk/helpers_objc/NSString+StdString.o",
            "third_party/webrtc/sdk/libwebrtc.a", "project/xcode_links/lib.a")]
        result = prepare.invalidate_compiled_outputs(self.src)
        self.assertEqual(result["removed_outputs"], len(outputs))
        self.assertTrue(all(not path.exists() for path in outputs))

    def test_real_sdk_roots_are_protected_from_output_invalidation(self):
        names = [f"{root}/platform/lib.a" for root in ("sdk", "xcode_links", "SDK", "Xcode_Links")]
        for name in names:
            self.write(self.out / name, "SDK library")
            for root in (self.out, self.src):
                for path in (self.out / name, self.out / Path(name).parts[0]):
                    relative = path.relative_to(root).as_posix()
                    for value in (relative, relative.replace("/", "\\")):
                        with self.subTest(root=root, value=value):
                            self.assertIsNone(prepare.inside_path(root, value, output=True))
        self.deps({})
        self.write(self.out / ".ninja_log", "# ninja log v5\n" + "".join(
            f"0\t1\t1\t{name}\tabc\n" for name in names))
        generated = prepare.invalidate_generated_outputs(self.src)
        self.assertEqual(generated, {"removed_outputs": 0, "unknown_outputs": names})
        self.deps({name: ["/external.h"] for name in names})
        dependencies = prepare.invalidate_external_dependencies(self.src, invalidate_all=True)
        self.assertEqual(dependencies["removed_outputs"], 0)
        self.assertEqual(len(dependencies["unknown_outputs"]), len(names))
        self.assertEqual(prepare.invalidate_compiled_outputs(self.src)["removed_outputs"], 0)
        for name in names:
            self.assertEqual((self.out / name).read_text(), "SDK library")

    def test_unrelated_sdk_named_ancestor_does_not_block_preparation(self):
        self.work = self.work / "out/Default/sdk/work"
        self.src = self.work / "src"
        self.out = self.src / "out/Default"
        self.fixture()
        with self.native_context():
            result = prepare.prepare(self.work, "macos", "arm64")
        self.assertTrue(result["ready_for_gn"])
        self.assertTrue((self.work / "upstream-cache-preparation.json").is_file())
        self.assertIsNone(prepare.inside_path(self.out, "sdk/keep.a", output=True))
        self.assertIsNone(prepare.inside_path(self.src, "out/Default/sdk/keep.a", output=True))

    def test_output_traversal_and_symlinks_never_delete_source_or_sdk(self):
        source = self.src / "include/a.h"
        sdk = self.write(self.work / "sdk/lib.a", "SDK")
        (self.out / "sdk").symlink_to(sdk.parent)
        (self.out / "obj/link.o").symlink_to(source)
        nested = self.out / "obj/third_party/webrtc/sdk"
        nested.mkdir(parents=True)
        (nested / "link.o").symlink_to(source)
        (nested / "linked").symlink_to(sdk.parent)
        self.deps({"../../include/a.h": ["/external.h"], "obj/link.o": ["/external.h"],
                   "sdk/lib.a": ["/external.h"], str(source): ["/external.h"],
                   "obj/third_party/webrtc/sdk/link.o": ["/external.h"],
                   "obj/third_party/webrtc/sdk/linked/lib.a": ["/external.h"]})
        result = prepare.invalidate_external_dependencies(self.src, invalidate_all=True)
        prepare.invalidate_compiled_outputs(self.src)
        self.assertEqual(len(result["unknown_outputs"]), 6)
        self.assertEqual(source.read_text(), "header")
        self.assertEqual(sdk.read_text(), "SDK")
        self.assertTrue((self.out / "obj/link.o").is_symlink())
        self.assertTrue((nested / "link.o").is_symlink())
        self.assertTrue((nested / "linked").is_symlink())

    def test_output_filter_keeps_traversal_and_metadata_protection(self):
        names = ("", "\0", "../outside.o", "obj/../inside.o", "/outside.o",
                 "C:\\outside.o", "obj/file:stream", "obj/third_party/webrtc/sdk/../file.o")
        names += tuple(f"obj/third_party/webrtc/sdk/{name}" for name in (
            *prepare.METADATA, "target.ninja"))
        for name in names:
            with self.subTest(name=name):
                self.assertIsNone(prepare.inside_path(self.out, name, output=True))

    def test_resolved_sdk_link_and_omitted_xcode_link_invalidate_readers(self):
        sdk = self.write(self.work / "sdk/stddef.h", "sdk")
        links = self.out / "sdk/xcode_links"
        links.mkdir(parents=True)
        (links / "MacOSX.sdk").symlink_to(sdk.parent)
        for name in ("sdk.o", "omitted.o", "internal.o"):
            self.object(name)
        self.deps({"obj/sdk.o": ["sdk/xcode_links/MacOSX.sdk/stddef.h"],
                   "obj/omitted.o": ["sdk/xcode_links/MacOSX26.0.sdk/stddef.h"],
                   "obj/internal.o": ["../../include/a.h"]})
        result = prepare.invalidate_external_dependencies(self.src)
        self.assertEqual(result["removed_outputs"], 2)
        self.assertTrue(sdk.exists())
        self.assertTrue((self.out / "obj/internal.o").exists())

    def test_omitted_external_inputs_are_distinct_from_missing_source(self):
        names = ("omitted.o", "source.o", "prefix.o", "both.o")
        for name in names:
            self.object(name)
        sdk = "sdk/xcode_links/MacOSX26.0.sdk"
        self.deps({"obj/omitted.o": [sdk + "/stddef.h"],
                   "obj/source.o": ["../../include/missing.h"],
                   "obj/prefix.o": [sdk + "-other/stddef.h"],
                   "obj/both.o": [sdk + "/stddef.h", "../../include/missing.h"]})
        result = prepare.invalidate_external_dependencies(
            self.src, external_inputs=["out/Default/" + sdk])
        self.assertEqual(result["external_dependency_outputs"], 2)
        self.assertEqual(result["missing_dependency_outputs"], 2)
        self.assertEqual(result["removed_outputs"], 4)
        self.assertEqual(result["input_reason_outputs"], {
            "omitted_external_input": 2, "missing_local_input": 3})
        self.assertEqual(result["input_samples"][0], {
            "output": "obj/omitted.o", "input": sdk + "/stddef.h",
            "reason": "omitted_external_input"})

    def test_recreated_omitted_sdk_links_remain_external_before_resolution(self):
        receipt = self.fixture()
        relative = "out/Default/sdk/xcode_links/MacOSX26.0.sdk"
        receipt["external_symlink_paths"] = [relative]
        self.write(self.src / restore.MARKER, json.dumps(receipt))
        link = self.src / relative
        link.parent.mkdir(parents=True)
        for target in (self.work / "host-sdk", self.src / "internal-sdk"):
            with self.subTest(target=target):
                self.write(target / "stddef.h", "header")
                link.symlink_to(target, target_is_directory=True)
                output = self.object("sdk.o")
                self.deps({"obj/sdk.o": ["sdk/xcode_links/MacOSX26.0.sdk/./stddef.h"]})
                (self.src / prepare.MARKER).unlink(missing_ok=True)
                with self.native_context():
                    result = prepare.prepare(self.work, "macos", "arm64")
                self.assertEqual(result["dependencies"]["input_reason_outputs"], {"omitted_external_input": 1})
                self.assertEqual(result["dependencies"]["external_dependency_outputs"], 1)
                self.assertFalse(output.exists())
                self.assertTrue((target / "stddef.h").exists())
                link.unlink()

    def test_removed_generated_readers_are_reported_separately(self):
        self.fixture()
        self.object("generated.o")
        independent = self.object("independent.o")
        self.write(self.out / "gen/header.h", "generated")
        self.write(self.out / ".ninja_log", "# ninja log v5\n0\t1\t1\tgen/header.h\tabc\n")
        self.deps({"obj/generated.o": ["gen/header.h"],
                   "obj/independent.o": ["../../include/a.h"]})
        with self.native_context():
            result = prepare.prepare(self.work, "macos", "arm64")
        dependencies = result["dependencies"]
        self.assertEqual(dependencies["input_reason_outputs"], {"removed_generated_input": 1})
        self.assertEqual(dependencies["removed_outputs"], 1)
        self.assertTrue(independent.exists())

    def test_dependency_diagnostic_samples_are_bounded_per_reader_reason(self):
        records = {}
        for index in range(40):
            name = f"sample-{index}.o"
            self.object(name)
            records["obj/" + name] = ["../../include/missing.h"] * 2
        self.deps(records)
        result = prepare.invalidate_external_dependencies(self.src)
        self.assertEqual(result["input_reason_outputs"], {"missing_local_input": 40})
        self.assertEqual(result["removed_outputs"], 40)
        self.assertEqual(len(result["input_samples"]), 32)

    def test_mac_nightly_without_chromium_stamp_reuses_native_tools(self):
        self.fixture()
        obj = self.object("a.o")
        self.deps({"obj/a.o": ["../../include/a.h"]})
        self.write(self.out / "Chromium.app/Contents/_CodeSignature/CodeResources", "signature")
        before = obj.stat().st_mtime_ns
        with self.native_context():
            inspection = prepare.prepare(self.work, "macos", "arm64", phase="inspect")
            result = prepare.prepare(self.work, "macos", "arm64")
        self.assertTrue(inspection["native_tools"])
        self.assertFalse((self.src / prepare.CLANG / "cr_build_revision").exists())
        self.assertFalse((self.src / prepare.RUST / "VERSION").exists())
        self.assertEqual(obj.stat().st_mtime_ns, before)
        self.assertEqual(result["removed_final_products"], ["Chromium.app"])
        self.assertEqual(result["counters"]["toolchain_invalidated_outputs"], 0)
        for name in ("build.ninja", "args.gn", ".ninja_deps", ".ninja_log"):
            self.assertTrue((self.out / name).exists())

    def test_linux_native_and_cross_inspect_finish_preserve_target_objects(self):
        root = self.work
        for arch, host_arch in (("x64", "x64"), ("arm64", "arm64"), ("arm64", "x64")):
            with self.subTest(arch=arch, host_arch=host_arch):
                self.work = root / f"{arch}-on-{host_arch}"
                self.src = self.work / "src"
                self.out = self.src / "out/Default"
                receipt = self.fixture("linux", arch, host_arch=host_arch)
                self.write(self.src / "include/a.h", "header")
                obj = self.object("internal.o")
                self.deps({"obj/internal.o": ["../../include/a.h"]})
                self.binary(self.out / "chrome", "linux", arch)
                go = prepare.generator_paths("linux", arch, host_arch=host_arch)["go"]
                self.write(self.src / go, "host go")
                preserved = {path: path.read_bytes() for path in (
                    self.src / restore.MARKER, *(self.out / name for name in prepare.METADATA))}
                before = obj.stat().st_mtime_ns
                output = io.StringIO()
                with self.native_context("linux", host_arch), redirect_stdout(output):
                    code = prepare.main(["--phase", "inspect", "--platform", "linux", "--arch", arch,
                                         "--workdir", str(self.work)])
                    self.assertEqual(code, 0)
                    inspection = json.loads(output.getvalue())
                    pending = json.loads((self.src / prepare.INSPECTION).read_text())
                    self.assertEqual(pending, inspection)
                    self.assertTrue(inspection["native_tools"])
                    self.assertFalse(inspection["host_mismatch"])
                    self.assertFalse(inspection["needs_invalidation"])
                    again = prepare.prepare(self.work, "linux", arch, phase="inspect")
                    self.assertFalse(again["needs_invalidation"])
                    self.assertFalse(again["generators_changed"])
                    result = prepare.prepare(self.work, "linux", arch)
                    resumed = prepare.prepare(self.work, "linux", arch)
                for report in (inspection, result, resumed):
                    self.assertEqual((report["platform"], report["arch"]), ("linux", arch))
                    self.assertEqual(report["host"], {"platform": "linux", "arch": host_arch})
                    self.assertEqual(report["source_identity"], receipt["identity"])
                    self.assertEqual(report["generator_fingerprint"]["go"]["path"], go.as_posix())
                    self.assertEqual(report["tools"]["node"]["path"],
                                     f"third_party/node/linux/node-linux-{host_arch}/bin/node")
                    for tool in report["tools"].values():
                        self.assertTrue(tool["native"])
                        self.assertEqual(tool["architectures"], [host_arch])
                self.assertTrue(result["ready_for_gn"])
                self.assertEqual(result["removed_final_products"], ["chrome"])
                self.assertEqual(result["counters"]["tool_swap_invalidations"], 0)
                self.assertEqual(result["counters"]["toolchain_invalidated_outputs"], 0)
                self.assertEqual(resumed["counters"]["tool_swap_invalidations"], 0)
                self.assertEqual(obj.stat().st_mtime_ns, before)
                for path, content in preserved.items():
                    self.assertEqual(path.read_bytes(), content)
                self.assertFalse((self.src / prepare.INSPECTION).exists())

    def test_linux_cross_never_executes_target_architecture_tools(self):
        self.fixture("linux", "arm64", donor_arch="arm64", host_arch="x64")
        obj = self.object("internal.o")
        self.deps({"obj/internal.o": ["../../include/a.h"]})
        with self.native_context("linux", "x64"), mock.patch.object(prepare.subprocess, "run") as run:
            inspection = prepare.prepare(self.work, "linux", "arm64", phase="inspect")
            self.assertTrue(inspection["needs_invalidation"])
            self.assertTrue(inspection["host_mismatch"])
            self.assertFalse(inspection["native_tools"])
            with self.assertRaisesRegex(ValueError, "cannot execute on the native host"):
                prepare.prepare(self.work, "linux", "arm64")
            run.assert_not_called()
            self.assertTrue(obj.exists())
        for relative in prepare.tool_paths("linux", "arm64", host_arch="x64").values():
            self.binary(self.src / relative, "linux", "x64")
        with self.native_context("linux", "x64"):
            result = prepare.prepare(self.work, "linux", "arm64")
        self.assertFalse(obj.exists())
        self.assertEqual(result["counters"]["tool_swap_invalidations"], 1)

    def test_linux_native_and_cross_compiler_and_runtime_changes_still_invalidate(self):
        root = self.work
        for host_arch in ("arm64", "x64"):
            with self.subTest(host_arch=host_arch):
                self.work = root / host_arch
                self.src = self.work / "src"
                self.out = self.src / "out/Default"
                self.fixture("linux", "arm64", host_arch=host_arch)
                self.write(self.src / "include/a.h", "header")
                self.deps({"obj/internal.o": ["../../include/a.h"]})
                obj = self.object("internal.o")
                with self.native_context("linux", host_arch):
                    prepare.prepare(self.work, "linux", "arm64", phase="inspect")
                    compiler = self.src / prepare.CLANG / "bin/clang"
                    self.write(compiler, compiler.read_bytes() + b"changed compiler")
                    inspection = prepare.prepare(self.work, "linux", "arm64", phase="inspect")
                    self.assertTrue(inspection["needs_invalidation"])
                    result = prepare.prepare(self.work, "linux", "arm64")
                    self.assertFalse(obj.exists())
                    self.assertEqual(result["counters"]["tool_swap_invalidations"], 1)
                    obj = self.object("internal.o")
                    self.write(self.src / prepare.CLANG / "lib/libclang.so", "changed runtime")
                    result = prepare.prepare(self.work, "linux", "arm64")
                self.assertFalse(obj.exists())
                self.assertEqual(result["counters"]["tool_swap_invalidations"], 1)

    def test_inspect_wrong_host_is_successful_json_without_execution(self):
        self.fixture("macos", "x64", donor_arch="arm64")
        output = io.StringIO()
        with mock.patch.object(prepare, "host_identity", return_value=("macos", "x64")), \
                mock.patch.object(prepare.subprocess, "run") as run, redirect_stdout(output):
            code = prepare.main(["--phase", "inspect", "--platform", "macos", "--arch", "x64", "--workdir", str(self.work)])
        self.assertEqual(code, 0)
        self.assertFalse(json.loads(output.getvalue())["native_tools"])
        run.assert_not_called()
        self.assertTrue(json.loads((self.src / prepare.INSPECTION).read_text())["needs_invalidation"])

    def test_inspect_writes_uploadable_native_probe_report(self):
        receipt = self.fixture()
        with self.native_context():
            result = prepare.prepare(self.work, "macos", "arm64", phase="inspect")
        report = json.loads((self.work / "upstream-cache-preparation.json").read_text())
        self.assertEqual(report, result)
        self.assertEqual(report["source_identity"], receipt["identity"])
        self.assertFalse(report["ready_for_gn"])
        self.assertFalse((self.src / prepare.MARKER).exists())

    def test_finish_failure_overwrites_stale_report_with_exact_probe_output(self):
        self.fixture()
        with self.native_context():
            prepare.prepare(self.work, "macos", "arm64")
        marker = (self.src / prepare.MARKER).read_bytes()
        obj = self.object("a.o")
        def run(command, **kwargs):
            failed = Path(command[0]).name == "bindgen"
            return mock.Mock(returncode=-6 if failed else 0, stdout=(
                "dyld: Library not loaded: @rpath/libclang.dylib\nReason: no LC_RPATH's found"
                if failed else "native tool"))
        with self.native_context(), mock.patch.object(prepare.subprocess, "run", side_effect=run):
            with self.assertRaisesRegex(ValueError, r"bindgen \(--version exited -6\)"):
                prepare.prepare(self.work, "macos", "arm64")
        report = json.loads((self.work / "upstream-cache-preparation.json").read_text())
        pending = json.loads((self.src / prepare.INSPECTION).read_text())
        self.assertFalse(report["ready_for_gn"])
        self.assertEqual(report["phase"], "finish")
        self.assertEqual(pending["phase"], "inspect")
        self.assertEqual(report["tools"], pending["tools"])
        self.assertIn("libclang.dylib", report["tools"]["bindgen"]["version"])
        self.assertIn("bindgen", report["error"])
        self.assertEqual((self.src / prepare.MARKER).read_bytes(), marker)
        self.assertTrue(obj.exists())

    def test_environment_failure_retains_probe_report_without_claiming_ready(self):
        self.fixture()
        with self.native_context(), mock.patch.object(prepare, "environment_identity", side_effect=ValueError("SDK missing")):
            with self.assertRaisesRegex(ValueError, "SDK missing"):
                prepare.prepare(self.work, "macos", "arm64")
        report = json.loads((self.work / "upstream-cache-preparation.json").read_text())
        self.assertFalse(report["ready_for_gn"])
        self.assertTrue(report["tools"]["bindgen"]["native"])
        self.assertEqual(report["operation"], "environment_identity")
        self.assertEqual(report["error"], "SDK missing")
        self.assertFalse((self.src / prepare.MARKER).exists())

    def test_early_failure_replaces_stale_success_without_losing_probe_evidence(self):
        self.fixture()
        for failure in ("receipt", "marker", "generator"):
            with self.subTest(failure=failure), self.native_context():
                prepare.prepare(self.work, "macos", "arm64")
                if failure == "receipt":
                    context = mock.patch.object(prepare, "verify_restored", side_effect=ValueError("receipt rejected"))
                    operation = "verify_restored"
                elif failure == "marker":
                    context = mock.patch.object(prepare, "_read_marker", side_effect=ValueError("malformed marker"))
                    operation = "read_preparation_markers"
                else:
                    context = mock.patch.object(prepare, "generator_fingerprint", side_effect=OSError("generator unreadable"))
                    operation = "generator_fingerprint"
                with context, self.assertRaises((ValueError, OSError)):
                    prepare.prepare(self.work, "macos", "arm64")
                report = json.loads((self.work / "upstream-cache-preparation.json").read_text())
                self.assertFalse(report["ready_for_gn"])
                self.assertEqual(report["operation"], operation)
                self.assertTrue(report["error"])
                self.assertEqual("tools" in report, failure == "generator")

    def test_mac_probe_runtime_is_scoped_after_system_shell_environment_loss(self):
        self.fixture()
        library = self.src / prepare.CLANG / "lib/libclang.dylib"
        self.binary(library, "macos", "arm64")
        self.binary(library.with_name("libc++abi.dylib"), "macos", "arm64")
        for inherited in ({}, {"DYLD_LIBRARY_PATH": str(library.parent), "DYLD_INSERT_LIBRARIES": "/bad"}):
            with self.subTest(inherited=inherited):
                views, commands = [], []
                def run(command, **kwargs):
                    commands.append(Path(command[0]).name)
                    env = kwargs["env"]
                    if commands[-1] == "bindgen":
                        view = Path(env["DYLD_LIBRARY_PATH"])
                        views.append(view)
                        self.assertEqual([path.name for path in view.iterdir()], ["libclang.dylib"])
                        self.assertEqual((view / "libclang.dylib").resolve(), library)
                        self.assertEqual(env, {"DYLD_LIBRARY_PATH": str(view)})
                    else:
                        self.assertEqual(env, {})
                    return mock.Mock(returncode=0, stdout="native")
                with self.native_context(), mock.patch.dict(os.environ, inherited, clear=True), \
                        mock.patch.object(prepare.subprocess, "run", side_effect=run):
                    result = prepare.prepare(self.work, "macos", "arm64", phase="inspect")
                    self.assertEqual(dict(os.environ), inherited)
                self.assertTrue(result["native_tools"])
                self.assertFalse(result["needs_invalidation"])
                self.assertEqual(set(commands), set(prepare.tool_paths("macos", "arm64")))
                self.assertEqual(len(views), 1)
                self.assertFalse(views[0].exists())

    def test_report_symlink_cannot_overwrite_external_file(self):
        self.fixture()
        target = self.write(self.work / "keep", "keep")
        (self.work / "upstream-cache-preparation.json").symlink_to(target)
        with self.native_context():
            with self.assertRaisesRegex(ValueError, "unsafe"):
                prepare.prepare(self.work, "macos", "arm64", phase="inspect")
        self.assertEqual(target.read_text(), "keep")

    def test_windows_is_not_executed_on_a_posix_host(self):
        self.fixture("windows", "x64")
        with mock.patch.object(prepare, "host_identity", return_value=("linux", "x64")), \
                mock.patch.object(prepare.subprocess, "run") as run:
            with self.assertRaisesRegex(ValueError, "native windows x64"):
                prepare.prepare(self.work, "windows", "x64", phase="inspect")
        run.assert_not_called()
        report = json.loads((self.work / "upstream-cache-preparation.json").read_text())
        self.assertFalse(report["ready_for_gn"])
        self.assertFalse((self.src / prepare.INSPECTION).exists())

    def test_only_native_and_linux_x64_to_arm64_host_target_pairs_are_allowed(self):
        targets = (("linux", "x64"), ("linux", "arm64"), ("macos", "x64"),
                   ("macos", "arm64"), ("windows", "x64"))
        for target in targets:
            for host in (*targets, ("windows", "arm64"), ("linux", "unknown")):
                if host == target or (target, host) == (("linux", "arm64"), ("linux", "x64")):
                    continue
                with self.subTest(target=target, host=host), \
                        mock.patch.object(prepare, "host_identity", return_value=host), \
                        mock.patch.object(prepare.subprocess, "run") as run:
                    with self.assertRaisesRegex(ValueError, "native .* runner is required"):
                        prepare.validate_native_tools(self.src, *target)
                    run.assert_not_called()
        with mock.patch.object(prepare, "host_identity", return_value=("windows", "arm64")):
            with self.assertRaisesRegex(ValueError, "unsupported restored build target"):
                prepare.validate_native_tools(self.src, "windows", "arm64")

    def test_windows_native_probe_uses_only_mocked_version_commands(self):
        self.fixture("windows", "x64")
        with self.native_context("windows", "x64"):
            result = prepare.prepare(self.work, "windows", "x64")
        self.assertTrue(result["native_tools"])

    def test_host_tool_failure_is_not_claimed_compatible(self):
        self.fixture("linux", "arm64")
        with mock.patch.object(prepare, "host_identity", return_value=("linux", "arm64")), \
                mock.patch.object(prepare.subprocess, "run", return_value=mock.Mock(returncode=1, stdout="GLIBC_2.38 not found")):
            result = prepare.validate_native_tools(self.src, "linux", "arm64")
        self.assertFalse(result["native_tools"])
        self.assertIn("GLIBC_2.38", result["tools"]["clang"]["version"])

    def test_unverified_source_fails_before_any_probe(self):
        with mock.patch.object(prepare.subprocess, "run") as run:
            with self.assertRaises((ValueError, OSError)):
                prepare.prepare(self.work, "linux", "x64", phase="inspect")
        run.assert_not_called()

    def test_resume_keeps_products_and_objects_until_environment_changes(self):
        self.fixture()
        internal = self.object("internal.o")
        self.object("external.o")
        self.deps({"obj/internal.o": ["../../include/a.h"], "obj/external.o": ["/unknown-sdk/header"]})
        with self.native_context():
            prepare.prepare(self.work, "macos", "arm64")
            external = self.object("external.o")
            product = self.write(self.out / "Chromium.app/Contents/MacOS/Chromium", "new product")
            result = prepare.prepare(self.work, "macos", "arm64")
            self.assertEqual(result["dependencies"]["removed_outputs"], 0)
            self.assertTrue(external.exists())
            with mock.patch.object(prepare, "environment_identity", return_value={"ImageVersion": "2", "SDK": "/sdk/27"}):
                result = prepare.prepare(self.work, "macos", "arm64")
        self.assertFalse(external.exists())
        self.assertTrue(internal.exists())
        self.assertTrue(product.exists())
        self.assertEqual(result["counters"]["environment_rechecks"], 1)
        self.assertEqual(result["counters"]["toolchain_invalidated_outputs"], 0)

    def test_host_swap_invalidates_compiled_and_host_binaries_but_not_sdk(self):
        self.fixture("macos", "x64", donor_arch="arm64")
        obj = self.object("internal.o")
        archive = self.object("rust.rlib")
        self.deps({"obj/internal.o": ["../../include/a.h"]})
        host_binary = self.out / "clang_arm64/mksnapshot"
        self.binary(host_binary, "macos", "arm64")
        sdk = self.write(self.out / "sdk/platform/lib.a", "SDK library")
        with self.native_context("macos", "x64"):
            prepare.prepare(self.work, "macos", "x64", phase="inspect")
            for name, relative in prepare.tool_paths("macos", "x64").items():
                if name != "gn":
                    self.binary(self.src / relative, "macos", "x64")
            result = prepare.prepare(self.work, "macos", "x64")
            self.assertGreaterEqual(result["counters"]["toolchain_invalidated_outputs"], 3)
            self.assertFalse(obj.exists())
            self.assertFalse(archive.exists())
            self.assertFalse(host_binary.exists())
            self.assertFalse((self.out / "gn").exists())
            self.assertTrue(sdk.exists())
            self.binary(self.out / "gn", "macos", "x64")
            obj = self.object("internal.o")
            result = prepare.prepare(self.work, "macos", "x64")
        self.assertTrue(obj.exists())
        self.assertEqual(result["counters"]["toolchain_invalidated_outputs"], 0)

    def test_repeated_inspect_cannot_hide_a_native_tool_replacement(self):
        self.fixture()
        obj = self.object("a.o")
        self.deps({"obj/a.o": ["../../include/a.h"]})
        with self.native_context():
            prepare.prepare(self.work, "macos", "arm64", phase="inspect")
            compiler = self.src / prepare.CLANG / "bin/clang"
            with compiler.open("ab") as stream:
                stream.write(b"new tool payload")
            again = prepare.prepare(self.work, "macos", "arm64", phase="inspect")
            self.assertTrue(again["needs_invalidation"])
            prepare.prepare(self.work, "macos", "arm64")
        self.assertFalse(obj.exists())

    def test_runtime_toolchain_content_change_not_just_version_invalidates(self):
        self.fixture()
        with self.native_context():
            prepare.prepare(self.work, "macos", "arm64")
            obj = self.object("a.o")
            self.deps({"obj/a.o": ["../../include/a.h"]})
            self.write(self.src / prepare.CLANG / "lib/libclang.dylib", "changed runtime")
            result = prepare.prepare(self.work, "macos", "arm64")
        self.assertFalse(obj.exists())
        self.assertEqual(result["counters"]["tool_swap_invalidations"], 1)

    def test_missing_node_link_does_not_discard_unrelated_compiled_objects(self):
        self.fixture("linux", "x64")
        obj = self.object("internal.o")
        node = self.src / prepare.tool_paths("linux", "x64")["node"]
        node.unlink()
        generated = self.write(self.out / "gen/node-output.h", "old generated")
        self.write(self.out / ".ninja_log", "# ninja log v5\n0\t1\t1\tgen/node-output.h\tabc\n")
        self.deps({"obj/internal.o": ["../../include/a.h"]})
        with self.native_context("linux", "x64"):
            inspection = prepare.prepare(self.work, "linux", "x64", phase="inspect")
            self.assertFalse(inspection["needs_invalidation"])
            self.binary(node, "linux", "x64")
            result = prepare.prepare(self.work, "linux", "x64")
        self.assertTrue(obj.exists())
        self.assertFalse(generated.exists())
        self.assertEqual(result["counters"]["toolchain_invalidated_outputs"], 0)
        self.assertEqual(result["generated_outputs"]["removed_outputs"], 1)

    def test_generator_content_change_rebuilds_generated_inputs_and_readers(self):
        self.fixture("linux", "x64")
        go = self.src / prepare.generator_paths("linux", "x64")["go"]
        self.write(go, "go version one")
        with self.native_context("linux", "x64"):
            prepare.prepare(self.work, "linux", "x64")
            independent = self.object("independent.o")
            dependent = self.object("generated.o")
            generated = self.write(self.out / "gen/go-output.h", "generated")
            self.deps({"obj/independent.o": ["../../include/a.h"],
                       "obj/generated.o": ["gen/go-output.h"]})
            self.write(self.out / ".ninja_log", "# ninja log v5\n0\t1\t1\tgen/go-output.h\tabc\n")
            self.write(go, "go version two")
            os.utime(go, ns=(1, 1))
            result = prepare.prepare(self.work, "linux", "x64")
        self.assertTrue(independent.exists())
        self.assertFalse(generated.exists())
        self.assertFalse(dependent.exists())
        self.assertEqual(result["counters"]["tool_swap_invalidations"], 0)
        self.assertEqual(result["counters"]["generator_rechecks"], 1)

    def test_generator_paths_have_native_defaults_and_explicit_host_override(self):
        for system, arch, node, go in (
                ("linux", "x64", "linux/node-linux-x64/bin/node", "linux-amd64/bin/go"),
                ("linux", "arm64", "linux/node-linux-arm64/bin/node", "linux-arm64/bin/go"),
                ("macos", "x64", "mac/node-darwin-x64/bin/node", "mac-amd64/bin/go"),
                ("macos", "arm64", "mac_arm64/node-darwin-arm64/bin/node", "mac-arm64/bin/go"),
                ("windows", "x64", "win/node.exe", "windows-amd64/bin/go.exe")):
            with self.subTest(system=system, arch=arch):
                paths = prepare.generator_paths(system, arch)
                self.assertEqual(paths, prepare.generator_paths(system, arch, host_arch=arch))
                self.assertEqual(paths["node"], Path("third_party/node") / node)
                self.assertEqual(paths["go"], Path("third_party/dawn/tools/golang") / go)
        self.assertEqual(prepare.generator_paths("linux", "arm64", host_arch="x64"),
                         prepare.generator_paths("linux", "x64"))

    def test_linux_tooling_links_follow_host_cpu_and_keep_native_defaults(self):
        root = self.work
        host_bin = root / "host-bin"
        for name in ("node", "go", "gperf", "clang-format"):
            self.write(host_bin / name, name)
        for arch, host_arch, kwargs in (("x64", "x64", {}), ("arm64", "arm64", {}),
                                        ("arm64", "x64", {"host_arch": "x64"})):
            with self.subTest(arch=arch, host_arch=host_arch):
                work = root / f"{arch}-on-{host_arch}"
                unused_cpu = "arm64" if host_arch == "x64" else "x64"
                unused = self.write(work / "src" / prepare.tool_paths("linux", unused_cpu)["node"], "unused node")
                with mock.patch.object(prepare.shutil, "which", side_effect=lambda name: str(host_bin / name)):
                    for _ in range(2):
                        prepare.prepare_tooling_links(work, "linux", arch, **kwargs)
                expected = prepare.generator_paths("linux", arch, host_arch=host_arch)
                for name, relative in expected.items():
                    path = work / "src" / relative
                    self.assertTrue(path.is_symlink())
                    self.assertEqual(path.resolve(), host_bin / name.replace("_", "-"))
                self.assertEqual((work / "src/third_party/node/linux/node-linux-x64/bin/node").resolve(), host_bin / "node")
                if host_arch == "x64":
                    self.assertEqual(unused.read_text(), "unused node")
                    self.assertFalse(unused.is_symlink())
                other_go = prepare.generator_paths("linux", unused_cpu)["go"]
                self.assertFalse((work / "src" / other_go).exists())

    def test_linux_cross_fingerprints_host_generators_not_target_generators(self):
        self.fixture("linux", "arm64", host_arch="x64")
        host_go = self.src / prepare.generator_paths("linux", "arm64", host_arch="x64")["go"]
        target_go = self.src / prepare.generator_paths("linux", "arm64")["go"]
        self.write(host_go, "host go one")
        self.write(target_go, "target go one")
        self.write(self.src / prepare.tool_paths("linux", "arm64")["node"], "target node")
        with self.native_context("linux", "x64"):
            prepare.prepare(self.work, "linux", "arm64")
            independent = self.object("independent.o")
            dependent = self.object("generated.o")
            generated = self.write(self.out / "gen/go-output.h", "generated")
            self.deps({"obj/independent.o": ["../../include/a.h"],
                       "obj/generated.o": ["gen/go-output.h"]})
            self.write(self.out / ".ninja_log", "# ninja log v5\n0\t1\t1\tgen/go-output.h\tabc\n")
            self.write(target_go, "target go two")
            result = prepare.prepare(self.work, "linux", "arm64")
            self.assertEqual(result["counters"]["generator_rechecks"], 0)
            self.assertTrue(generated.exists())
            self.assertTrue(dependent.exists())
            self.write(host_go, "host go two")
            result = prepare.prepare(self.work, "linux", "arm64")
        self.assertTrue(independent.exists())
        self.assertFalse(dependent.exists())
        self.assertFalse(generated.exists())
        self.assertEqual(result["counters"]["generator_rechecks"], 1)
        self.assertEqual(result["counters"]["tool_swap_invalidations"], 0)

    def test_arm64_repair_accepts_actual_eight_space_llvm_arguments(self):
        source = ("from build import GetHostSysrootPlatform, GitRevert\n"
                  "openssl = f'{OPENSSL_CIPD_LINUX_AMD_PATH}'\n"
                  "def triple():\n    return 'x86_64-unknown-linux-gnu'\n"
                  "def llvm():\n    flags = [\n        '--disable-asserts',\n        '--no-tools',\n    ]\n"
                  "    DownloadDebianSysroot('amd64', args.skip_checkout)\n")
        path = self.write(self.src / "tools/rust/build_rust.py", source)
        prepare.repair_linux_arm64_tool_script(self.src)
        changed = path.read_text()
        self.assertIn("        '--host-cc=clang',", changed)
        compile(changed, str(path), "exec")
        prepare.repair_linux_arm64_tool_script(self.src)
        self.assertEqual(changed, path.read_text())

    def test_linux_and_windows_relink_final_products(self):
        for platform, names in (("linux", ["chrome", "chrome_crashpad_handler", "chrome_sandbox"]),
                                ("windows", ["chrome.exe", "chrome.dll", "chrome_elf.dll"])):
            with self.subTest(platform=platform):
                for name in names:
                    self.write(self.out / name, "old binary")
                self.assertEqual(prepare.remove_final_products(self.src, platform), names)
                self.assertTrue((self.out / "obj").exists())

    def test_final_product_symlink_is_rejected(self):
        target = self.work / "user-app"
        target.mkdir()
        (self.out / "Chromium.app").symlink_to(target)
        with self.assertRaisesRegex(ValueError, "symlinked final"):
            prepare.remove_final_products(self.src, "macos")
        self.assertTrue(target.exists())

    def test_signed_bundle_internal_sdk_link_is_not_followed(self):
        sdk = self.write(self.work / "sdk/header", "SDK")
        self.write(self.out / "Chromium.app/Contents/_CodeSignature/CodeResources", "signed")
        (self.out / "Chromium.app/Contents/linked").symlink_to(sdk.parent)
        obj = self.object("a.o")
        prepare.remove_final_products(self.src, "macos")
        self.assertTrue(sdk.exists())
        self.assertTrue(obj.exists())

    def test_marker_symlink_cannot_overwrite_external_file(self):
        self.fixture()
        target = self.write(self.work / "keep", "keep")
        (self.src / prepare.MARKER).symlink_to(target)
        with self.assertRaisesRegex(ValueError, "unsafe"):
            prepare.prepare(self.work, "macos", "arm64")
        self.assertEqual(target.read_text(), "keep")

    def sysroot(self, cpu, version="one"):
        root = self.src / f"build/linux/debian_bullseye_{cpu}-sysroot"
        self.write(root / "usr/include/fixture.h", f"#define VALUE {version}\n")
        return self.write(root / ".stamp", f"https://example.invalid/{cpu}/{version}")

    def test_linux_sysroot_initial_replacement_and_installation_invalidate(self):
        root = self.work
        for cpu in ("amd64", "arm64"):
            for state in ("installed", "missing", "missing-stamp"):
                with self.subTest(cpu=cpu, state=state):
                    self.work = root / f"{cpu}-{state}"
                    self.src = self.work / "src"
                    self.out = self.src / "out/Default"
                    self.fixture("linux", "arm64", host_arch="x64")
                    self.sysroot("arm64" if cpu == "amd64" else "amd64")
                    if state != "missing":
                        stamp = self.sysroot(cpu)
                        if state == "missing-stamp":
                            stamp.unlink()
                    obj = self.object("sysroot.o")
                    archive = self.object("sysroot.rlib")
                    self.deps({"obj/sysroot.o": []})
                    metadata = {name: (self.out / name).read_bytes() for name in prepare.METADATA}
                    with self.native_context("linux", "x64"):
                        before = prepare.prepare(self.work, "linux", "arm64", phase="inspect")
                        self.assertFalse(before["sysroots_changed"])
                        self.assertEqual(len(before["sysroot_identity"]), 2)
                        stamp = self.sysroot(cpu, "two")
                        for _ in range(2):
                            pending = prepare.prepare(self.work, "linux", "arm64", phase="inspect")
                            self.assertTrue(pending["sysroots_changed"])
                            self.assertFalse(pending["needs_invalidation"])
                            self.assertTrue(obj.exists())
                        result = prepare.prepare(self.work, "linux", "arm64")
                    self.assertFalse(obj.exists())
                    self.assertFalse(archive.exists())
                    self.assertEqual(result["counters"]["sysroot_invalidations"], 1)
                    self.assertEqual(result["counters"]["tool_swap_invalidations"], 0)
                    self.assertFalse(result["sysroots_changed"])
                    self.assertTrue(stamp.is_file())
                    for name, content in metadata.items():
                        self.assertEqual((self.out / name).read_bytes(), content)

    def test_linux_sysroot_resume_content_change_preserves_stat_and_invalidates(self):
        root = self.work
        for cpu in ("amd64", "arm64"):
            with self.subTest(cpu=cpu):
                self.work = root / cpu
                self.src = self.work / "src"
                self.out = self.src / "out/Default"
                self.fixture("linux", "arm64", host_arch="x64")
                stamps = {name: self.sysroot(name) for name in ("amd64", "arm64")}
                self.deps({"obj/sysroot.o": []})
                with self.native_context("linux", "x64"):
                    first = prepare.prepare(self.work, "linux", "arm64")
                    obj = self.object("sysroot.o")
                    stamp = stamps[cpu]
                    header = stamp.parent / "usr/include/fixture.h"
                    times = {path: path.stat() for path in (stamp, header)}
                    self.sysroot(cpu, "two")
                    for path, info in times.items():
                        os.utime(path, ns=(info.st_atime_ns, info.st_mtime_ns))
                        self.assertEqual(path.stat().st_size, info.st_size)
                    result = prepare.prepare(self.work, "linux", "arm64")
                    self.assertNotEqual(first["sysroot_identity"], result["sysroot_identity"])
                    self.assertFalse(obj.exists())
                    self.assertEqual(result["counters"]["sysroot_invalidations"], 1)
                    self.assertEqual(result["counters"]["tool_swap_invalidations"], 0)
                    self.binary(self.out / "gn", "linux", "x64")
                    self.object("sysroot.o")
                    before = obj.stat().st_mtime_ns
                    prepare.prepare(self.work, "linux", "arm64", phase="inspect")
                    resumed = prepare.prepare(self.work, "linux", "arm64")
                self.assertEqual(resumed["counters"]["sysroot_invalidations"], 0)
                self.assertEqual(resumed["counters"]["toolchain_invalidated_outputs"], 0)
                self.assertEqual(obj.stat().st_mtime_ns, before)

    def test_linux_sysroot_change_stays_pending_after_reversion_and_failed_finish(self):
        self.fixture("linux", "arm64", host_arch="x64")
        stamp = self.sysroot("amd64")
        self.sysroot("arm64")
        obj = self.object("sysroot.o")
        self.deps({"obj/sysroot.o": []})
        with self.native_context("linux", "x64"):
            first = prepare.prepare(self.work, "linux", "arm64", phase="inspect")
            info = stamp.stat()
            self.write(stamp, "replacement")
            prepare.prepare(self.work, "linux", "arm64", phase="inspect")
            self.sysroot("amd64")
            os.utime(stamp, ns=(info.st_atime_ns, info.st_mtime_ns))
            restored = prepare.prepare(self.work, "linux", "arm64", phase="inspect")
            self.assertEqual(first["sysroot_identity"], restored["sysroot_identity"])
            self.assertTrue(restored["sysroots_changed"])
            with mock.patch.object(prepare, "environment_identity", side_effect=ValueError("unavailable")):
                with self.assertRaisesRegex(ValueError, "unavailable"):
                    prepare.prepare(self.work, "linux", "arm64")
            self.assertTrue(obj.exists())
            result = prepare.prepare(self.work, "linux", "arm64")
        self.assertFalse(obj.exists())
        self.assertEqual(result["counters"]["sysroot_invalidations"], 1)

    def test_linux_sysroot_failed_direct_finish_persists_change_before_reversion(self):
        self.fixture("linux", "arm64", host_arch="x64")
        stamp = self.sysroot("amd64")
        self.sysroot("arm64")
        with self.native_context("linux", "x64"):
            prepare.prepare(self.work, "linux", "arm64")
            obj = self.object("internal.o")
            self.deps({"obj/internal.o": []})
            info = stamp.stat()
            self.write(stamp, "replacement")
            with mock.patch.object(prepare, "environment_identity", side_effect=ValueError("unavailable")):
                with self.assertRaisesRegex(ValueError, "unavailable"):
                    prepare.prepare(self.work, "linux", "arm64")
            pending = json.loads((self.src / prepare.INSPECTION).read_text())
            self.assertTrue(pending["sysroots_changed"])
            self.sysroot("amd64")
            os.utime(stamp, ns=(info.st_atime_ns, info.st_mtime_ns))
            result = prepare.prepare(self.work, "linux", "arm64")
        self.assertFalse(obj.exists())
        self.assertEqual(result["counters"]["sysroot_invalidations"], 1)

    def test_linux_sysroot_direct_first_finish_detects_installation(self):
        root = self.work
        for cpu in ("amd64", "arm64"):
            with self.subTest(cpu=cpu):
                self.work = root / cpu
                self.src = self.work / "src"
                self.out = self.src / "out/Default"
                self.fixture("linux", "arm64", host_arch="x64")
                self.sysroot("arm64" if cpu == "amd64" else "amd64")
                obj = self.object("internal.o")
                self.deps({"obj/internal.o": []})
                with self.native_context("linux", "x64"):
                    prepare.prepare(self.work, "linux", "arm64", phase="inspect")
                    self.sysroot(cpu)
                    result = prepare.prepare(self.work, "linux", "arm64")
                self.assertFalse(obj.exists())
                self.assertEqual(result["counters"]["sysroot_invalidations"], 1)

    def test_linux_unchanged_sysroots_and_host_relinks_keep_native_and_cross_objects(self):
        root = self.work
        for arch, host in (("x64", "x64"), ("arm64", "arm64"), ("arm64", "x64")):
            with self.subTest(arch=arch, host=host):
                self.work = root / f"{arch}-{host}"
                self.src = self.work / "src"
                self.out = self.src / "out/Default"
                self.fixture("linux", arch, host_arch=host)
                for cpu in ("amd64", "arm64"):
                    self.sysroot(cpu)
                obj = self.object("internal.o")
                self.write(self.src / "include/a.h", "header")
                self.deps({"obj/internal.o": ["../../include/a.h"]})
                before = obj.stat().st_mtime_ns
                host_bin = self.work / "host-bin"
                for name in ("node", "go", "gperf", "clang-format"):
                    self.binary(host_bin / name, "linux", host)
                with self.native_context("linux", host), \
                        mock.patch.object(prepare.shutil, "which", side_effect=lambda name: str(host_bin / name)):
                    prepare.prepare(self.work, "linux", arch, phase="inspect")
                    prepare.prepare_tooling_links(self.work, "linux", arch, host_arch=host)
                    prepare.prepare(self.work, "linux", arch, phase="inspect")
                    prepare.prepare_tooling_links(self.work, "linux", arch, host_arch=host)
                    first = prepare.prepare(self.work, "linux", arch)
                    prepare.prepare(self.work, "linux", arch, phase="inspect")
                    prepare.prepare_tooling_links(self.work, "linux", arch, host_arch=host)
                    resumed = prepare.prepare(self.work, "linux", arch)
                for report in (first, resumed):
                    self.assertEqual(len(report["sysroot_identity"]), 1 if arch == host else 2)
                    self.assertEqual(report["counters"]["sysroot_invalidations"], 0)
                    self.assertEqual(report["counters"]["toolchain_invalidated_outputs"], 0)
                self.assertEqual(obj.stat().st_mtime_ns, before)

    def test_linux_legacy_environment_stamps_support_unchanged_and_changed_resume(self):
        root = self.work
        environment_identity = prepare.environment_identity
        for cpu in ("amd64", "arm64"):
            for state in ("unchanged", "changed", "missing", "unknown"):
                with self.subTest(cpu=cpu, state=state):
                    self.work = root / f"{cpu}-{state}"
                    self.src = self.work / "src"
                    self.out = self.src / "out/Default"
                    self.fixture("linux", "arm64", host_arch="x64")
                    stamps = {name: self.sysroot(name) for name in ("amd64", "arm64")}
                    if state == "missing":
                        stamps[cpu].unlink()
                    with self.native_context("linux", "x64"), \
                            mock.patch.object(prepare, "environment_identity", side_effect=environment_identity):
                        previous = prepare.prepare(self.work, "linux", "arm64")
                        previous.pop("sysroot_identity")
                        previous.pop("sysroots_changed")
                        if state == "unknown":
                            previous["environment"].pop("sysroots")
                        self.write(self.src / prepare.MARKER, json.dumps(previous))
                        self.object("internal.o")
                        self.deps({"obj/internal.o": []})
                        if state in ("changed", "missing"):
                            self.sysroot(cpu, "updated stamp")
                        pending = prepare.prepare(self.work, "linux", "arm64", phase="inspect")
                        self.assertEqual(pending["sysroots_changed"], state != "unchanged")
                        result = prepare.prepare(self.work, "linux", "arm64")
                    self.assertEqual(result["counters"]["sysroot_invalidations"], int(state != "unchanged"))
                    self.assertEqual((self.out / "obj/internal.o").exists(), state == "unchanged")

    def test_linux_legacy_pending_uses_reliable_old_environment_without_invalidation(self):
        self.fixture("linux", "arm64", host_arch="x64")
        self.sysroot("amd64")
        self.sysroot("arm64")
        environment_identity = prepare.environment_identity
        with self.native_context("linux", "x64"), \
                mock.patch.object(prepare, "environment_identity", side_effect=environment_identity):
            previous = prepare.prepare(self.work, "linux", "arm64")
            previous.pop("sysroot_identity")
            previous.pop("sysroots_changed")
            self.write(self.src / prepare.MARKER, json.dumps(previous))
            pending = dict(previous, phase="inspect")
            pending.pop("environment")
            self.write(self.src / prepare.INSPECTION, json.dumps(pending))
            obj = self.object("internal.o")
            self.deps({"obj/internal.o": []})
            result = prepare.prepare(self.work, "linux", "arm64")
        self.assertTrue(obj.exists())
        self.assertEqual(result["counters"]["sysroot_invalidations"], 0)

    def test_linux_legacy_pending_without_baseline_invalidates_conservatively(self):
        self.fixture("linux", "arm64", host_arch="x64")
        self.sysroot("amd64")
        self.sysroot("arm64")
        obj = self.object("internal.o")
        self.deps({"obj/internal.o": []})
        with self.native_context("linux", "x64"):
            pending = prepare.prepare(self.work, "linux", "arm64", phase="inspect")
            pending.pop("sysroot_identity")
            pending.pop("sysroots_changed")
            self.write(self.src / prepare.INSPECTION, json.dumps(pending))
            result = prepare.prepare(self.work, "linux", "arm64")
        self.assertFalse(obj.exists())
        self.assertEqual(result["counters"]["sysroot_invalidations"], 1)

    def test_sysroot_identity_rejects_unsafe_paths_and_nonregular_stamps(self):
        root = self.work
        for location in ("build", "build/linux", "build/linux/debian_bullseye_amd64-sysroot",
                         "build/linux/debian_bullseye_amd64-sysroot/.stamp"):
            for kind in ("internal-link", "external-link", "dangling-link", "wrong-type"):
                with self.subTest(location=location, kind=kind):
                    src = root / (location.replace("/", "_") + kind) / "src"
                    src.mkdir(parents=True)
                    path = src / location
                    path.parent.mkdir(parents=True, exist_ok=True)
                    target = (src if kind == "internal-link" else src.parent) / "target"
                    if kind == "wrong-type":
                        if path.name == ".stamp":
                            path.mkdir()
                        else:
                            path.write_text("not a directory")
                    else:
                        if kind != "dangling-link":
                            if path.name == ".stamp":
                                target.write_text("stamp")
                            else:
                                target.mkdir()
                        path.symlink_to(target)
                    with self.assertRaises((ValueError, OSError)):
                        prepare.linux_sysroot_identity(src, "arm64", host_arch="x64")
                    self.assertTrue(path.exists() or path.is_symlink())
        for arch, host in (("../x64", "x64"), ("arm64", "../../x64"), ("amd64", "x64")):
            with self.assertRaisesRegex(ValueError, "unsupported Linux sysroot architecture"):
                prepare.linux_sysroot_identity(self.src, arch, host_arch=host)

    def test_sysroot_path_failure_preserves_objects_and_reports_not_ready(self):
        self.fixture("linux", "arm64", host_arch="x64")
        stamp = self.sysroot("amd64")
        self.sysroot("arm64")
        with self.native_context("linux", "x64"):
            prepare.prepare(self.work, "linux", "arm64")
            marker = (self.src / prepare.MARKER).read_bytes()
            obj = self.object("internal.o")
            stamp.unlink()
            target = self.write(self.work / "external-stamp", "keep")
            stamp.symlink_to(target)
            with self.assertRaisesRegex(ValueError, "unsafe"):
                prepare.prepare(self.work, "linux", "arm64")
        report = json.loads((self.work / "upstream-cache-preparation.json").read_text())
        self.assertFalse(report["ready_for_gn"])
        self.assertEqual(report["operation"], "linux_sysroot_identity")
        self.assertEqual((self.src / prepare.MARKER).read_bytes(), marker)
        self.assertTrue(obj.exists())
        self.assertEqual(target.read_text(), "keep")

    def test_sysroot_stamp_hardlinks_special_files_and_oversize_are_rejected(self):
        stamp = self.sysroot("amd64")
        stamp.unlink()
        target = self.write(self.work / "stamp", "stamp")
        os.link(target, stamp)
        with self.assertRaisesRegex(ValueError, "invalid sysroot stamp"):
            prepare.linux_sysroot_identity(self.src, "x64", host_arch="x64")
        stamp.unlink()
        if hasattr(os, "mkfifo"):
            os.mkfifo(stamp)
            with self.assertRaisesRegex(ValueError, "invalid sysroot stamp"):
                prepare.linux_sysroot_identity(self.src, "x64", host_arch="x64")
            stamp.unlink()
        self.write(stamp, "x" * 4097)
        with self.assertRaisesRegex(ValueError, "oversized sysroot stamp"):
            prepare.linux_sysroot_identity(self.src, "x64", host_arch="x64")

    def test_sysroot_first_class_markers_are_tracked_and_cannot_be_links(self):
        stamp = self.sysroot("amd64")
        before = prepare.linux_sysroot_identity(self.src, "x64", host_arch="x64")
        marker = self.write(stamp.parent / ".fixture_is_first_class_gcs", "first class")
        after = prepare.linux_sysroot_identity(self.src, "x64", host_arch="x64")
        self.assertNotEqual(before, after)
        marker.unlink()
        marker.symlink_to(stamp)
        with self.assertRaisesRegex(ValueError, "unsafe"):
            prepare.linux_sysroot_identity(self.src, "x64", host_arch="x64")

    def test_sysroot_invalidation_does_not_follow_output_links_or_delete_sdk(self):
        self.fixture("linux", "arm64", host_arch="x64")
        stamp = self.sysroot("amd64")
        self.sysroot("arm64")
        sdk = self.write(self.out / "sdk/lib.a", "SDK")
        target = self.write(self.work / "outside.o", "outside object")
        (self.out / "obj/link.o").symlink_to(target)
        obj = self.object("internal.o")
        self.deps({"obj/internal.o": [], "obj/link.o": [], "sdk/lib.a": []})
        with self.native_context("linux", "x64"):
            prepare.prepare(self.work, "linux", "arm64", phase="inspect")
            self.write(stamp, "replacement")
            result = prepare.prepare(self.work, "linux", "arm64")
        self.assertEqual(result["counters"]["sysroot_invalidations"], 1)
        self.assertFalse(obj.exists())
        self.assertEqual(sdk.read_text(), "SDK")
        self.assertEqual(target.read_text(), "outside object")
        self.assertTrue((self.out / "obj/link.o").is_symlink())

    def test_non_linux_preparation_does_not_collect_sysroot_identities(self):
        root = self.work
        for platform, arch in (("macos", "arm64"), ("windows", "x64")):
            with self.subTest(platform=platform):
                self.work = root / platform
                self.src = self.work / "src"
                self.out = self.src / "out/Default"
                self.fixture(platform, arch)
                with self.native_context(platform, arch), mock.patch.object(prepare, "linux_sysroot_identity") as identity:
                    prepare.prepare(self.work, platform, arch, phase="inspect")
                    result = prepare.prepare(self.work, platform, arch)
                identity.assert_not_called()
                self.assertNotIn("sysroot_identity", result)
                self.assertNotIn("sysroot_invalidations", result["counters"])

    def test_environment_records_runner_image_and_sdk_build_not_generated_graph(self):
        self.fixture()
        sdk = self.work / "SDK"
        self.write(sdk / "SDKSettings.json", '{"Version": "26.0"}')
        def run(command, **kwargs):
            values = {"--show-sdk-path": str(sdk), "--show-sdk-version": "26.0",
                      "--show-sdk-build-version": "25A", "-version": "Xcode 26\nBuild version 17A",
                      "--print-path": "/Applications/Xcode.app/Contents/Developer"}
            return mock.Mock(stdout=values[command[-1]], returncode=0)
        with mock.patch.dict(os.environ, {"ImageOS": "macos15", "ImageVersion": "v1", "GITHUB_JOB": "build-1"}), \
                mock.patch.object(prepare.subprocess, "run", side_effect=run):
            first = prepare.environment_identity(self.src, "macos")
            self.write(self.out / "build.ninja", "new graph")
            self.assertEqual(first, prepare.environment_identity(self.src, "macos"))
            with mock.patch.dict(os.environ, {"ImageVersion": "v2"}):
                self.assertNotEqual(first, prepare.environment_identity(self.src, "macos"))
        self.assertEqual(first["xcrun --sdk macosx --show-sdk-build-version"], "25A")
        self.assertEqual(first["sdks"][0]["root"]["path"], str(sdk))


if __name__ == "__main__":
    unittest.main()
