"""Restored trees retain internal objects and never execute foreign donor tools."""
import io
import json
import os
from pathlib import Path
import struct
import tempfile
import unittest
from contextlib import ExitStack, redirect_stdout
from unittest import mock

from tools import prepare_restored_build as prepare
from tools import restore_upstream_cache as restore


class PrepareRestoredBuildTest(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.work = Path(self.temporary.name)
        self.src = self.work / "src"
        self.out = self.src / "out/Default"
        (self.out / "obj").mkdir(parents=True)
        (self.src / "include").mkdir()
        (self.src / "include/a.h").write_text("header")

    def write(self, path, content):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content.encode() if isinstance(content, str) else content)
        return path

    def object(self, name):
        return self.write(self.out / "obj" / name, "object")

    def binary(self, path, platform, arch):
        header = bytearray(64)
        if platform == "macos":
            header[:4] = b"\xcf\xfa\xed\xfe"
            struct.pack_into("<I", header, 4, {"x64": 0x1000007, "arm64": 0x100000C}[arch])
        elif platform == "linux":
            header[:6] = b"\x7fELF\x02\x01"
            struct.pack_into("<H", header, 18, {"x64": 62, "arm64": 183}[arch])
        else:
            header[:2] = b"MZ"
            struct.pack_into("<I", header, 60, 64)
            header.extend(b"PE\0\0" + struct.pack("<H", 0x8664))
        self.write(path, header)
        path.chmod(0o755)

    def fixture(self, platform="macos", arch="arm64", donor_arch=None):
        identity, _, manifest = restore.identities(prepare.ROOT, platform, arch)
        version = "\n".join(f"{key}={value}" for key, value in zip(
            ("MAJOR", "MINOR", "BUILD", "PATCH"), identity["chromium_version"].split(".")))
        self.write(self.src / "chrome/VERSION", version)
        self.write(self.src / "BUILD.gn", "# source")
        self.write(self.out / "args.gn", f'target_cpu = "{arch}"\n')
        self.write(self.out / "build.ninja", "# regenerated by the native builder")
        self.write(self.out / ".ninja_log", "# ninja log v5\n")
        self.write(self.out / ".ninja_deps", b"# ninjadeps\n\x04\0\0\0")
        receipt = {"schema_version": 1, "owner": restore.OWNER, "status": "restored",
                   "extraction_scope": restore.fetcher.SOURCE_SCOPE, "identity": identity,
                   "manifest": manifest, "platform": platform, "arch": arch,
                   "original_args": restore.source_args(self.src, identity), "external_symlink_paths": []}
        self.write(self.src / restore.MARKER, json.dumps(receipt))
        for relative in prepare.tool_paths(platform, arch).values():
            self.binary(self.src / relative, platform, donor_arch or arch)
        # Upstream macOS resources have nested nightly components and no Chromium stamps.
        if platform == "macos":
            rust = self.src / prepare.RUST
            for name in ("rustc", "cargo"):
                path = rust / "bin" / name
                destination = rust / name / "bin" / name
                destination.parent.mkdir(parents=True)
                path.rename(destination)
                path.symlink_to(Path("..") / name / "bin" / name)
            self.write(rust / "version", "1.91.0-nightly (2026-06-16)")
        return receipt

    def deps(self, records):
        paths = list(dict.fromkeys(name for output, inputs in records.items() for name in (output, *inputs)))
        data = bytearray(b"# ninjadeps\n\x04\0\0\0")
        for index, name in enumerate(paths):
            payload = name.encode()
            payload += b"\0" * (-len(payload) % 4)
            payload += struct.pack("<I", ~index & 0xffffffff)
            data += struct.pack("<I", len(payload)) + payload
        for output, inputs in records.items():
            values = [paths.index(output), 1, 0] + [paths.index(name) for name in inputs]
            payload = struct.pack(f"<{len(values)}I", *values)
            data += struct.pack("<I", 0x80000000 | len(payload)) + payload
        self.write(self.out / ".ninja_deps", data)

    def native_context(self, platform="macos", arch="arm64"):
        stack = ExitStack()
        stack.enter_context(mock.patch.object(prepare, "host_identity", return_value=(platform, arch)))
        stack.enter_context(mock.patch.object(prepare.subprocess, "run", return_value=mock.Mock(
            returncode=0, stdout="thirdparty LLVM 23 / rustc nightly")))
        stack.enter_context(mock.patch.object(prepare, "environment_identity", return_value={"ImageOS": "macos15", "ImageVersion": "1", "SDK": "/sdk/26"}))
        return stack

    def test_internal_dependencies_keep_object_and_mtime(self):
        output = self.object("a.o")
        before = output.stat().st_mtime_ns
        self.deps({"obj/a.o": ["../../include/a.h"]})
        result = prepare.invalidate_external_dependencies(self.src)
        self.assertEqual(result["removed_outputs"], 0)
        self.assertEqual(output.stat().st_mtime_ns, before)

    def test_external_and_missing_dependencies_rebuild_only_affected_outputs(self):
        for name in ("a.o", "b.o", "c.obj", "d.o", "e.o"):
            self.object(name)
        self.deps({"obj/a.o": ["../../include/a.h"], "obj/b.o": ["/Applications/Xcode.app/SDK/stdlib.h"],
                   "obj\\c.obj": ["C:\\Program Files\\SDK\\stddef.h"], "obj/d.o": ["../../../external.h"],
                   "obj/e.o": ["../../include/missing.h"]})
        result = prepare.invalidate_external_dependencies(self.src)
        self.assertEqual(result["external_dependency_outputs"], 3)
        self.assertEqual(result["missing_dependency_outputs"], 1)
        self.assertEqual(result["removed_outputs"], 4)
        self.assertEqual([path.name for path in (self.out / "obj").iterdir()], ["a.o"])

    def test_unknown_external_dependency_invalidates_every_reader(self):
        for name in ("a.o", "b.o", "c.o"):
            self.object(name)
        self.deps({"obj/a.o": ["/unknown/header"], "obj/b.o": ["/unknown/header"], "obj/c.o": ["../../include/a.h"]})
        result = prepare.invalidate_external_dependencies(self.src)
        self.assertEqual(result["removed_outputs"], 2)
        self.assertTrue((self.out / "obj/c.o").exists())

    def test_output_traversal_and_symlinks_never_delete_source_or_sdk(self):
        source = self.src / "include/a.h"
        sdk = self.write(self.work / "sdk/lib.a", "SDK")
        (self.out / "sdk").symlink_to(sdk.parent)
        (self.out / "obj/link.o").symlink_to(source)
        self.deps({"../../include/a.h": ["/external.h"], "obj/link.o": ["/external.h"],
                   "sdk/lib.a": ["/external.h"], str(source): ["/external.h"]})
        result = prepare.invalidate_external_dependencies(self.src, invalidate_all=True)
        prepare.invalidate_compiled_outputs(self.src)
        self.assertEqual(len(result["unknown_outputs"]), 4)
        self.assertEqual(source.read_text(), "header")
        self.assertEqual(sdk.read_text(), "SDK")
        self.assertTrue((self.out / "obj/link.o").is_symlink())

    def test_resolved_sdk_link_and_omitted_xcode_link_invalidate_readers(self):
        sdk = self.write(self.work / "sdk/stddef.h", "sdk")
        links = self.out / "sdk/xcode_links"
        links.mkdir(parents=True)
        (links / "MacOSX.sdk").symlink_to(sdk.parent)
        for name in ("sdk.o", "omitted.o", "internal.o"):
            self.object(name)
        self.deps({"obj/sdk.o": ["sdk/xcode_links/MacOSX.sdk/stddef.h"],
                   "obj/omitted.o": ["sdk/xcode_links/MacOSX26.0.sdk/stddef.h"],
                   "obj/internal.o": ["../../include/a.h"]})
        result = prepare.invalidate_external_dependencies(self.src)
        self.assertEqual(result["removed_outputs"], 2)
        self.assertTrue(sdk.exists())
        self.assertTrue((self.out / "obj/internal.o").exists())

    def test_mac_nightly_without_chromium_stamp_reuses_native_tools(self):
        self.fixture()
        obj = self.object("a.o")
        self.deps({"obj/a.o": ["../../include/a.h"]})
        self.write(self.out / "Chromium.app/Contents/_CodeSignature/CodeResources", "signature")
        before = obj.stat().st_mtime_ns
        with self.native_context():
            inspection = prepare.prepare(self.work, "macos", "arm64", phase="inspect")
            result = prepare.prepare(self.work, "macos", "arm64")
        self.assertTrue(inspection["native_tools"])
        self.assertFalse((self.src / prepare.CLANG / "cr_build_revision").exists())
        self.assertFalse((self.src / prepare.RUST / "VERSION").exists())
        self.assertEqual(obj.stat().st_mtime_ns, before)
        self.assertEqual(result["removed_final_products"], ["Chromium.app"])
        self.assertEqual(result["counters"]["toolchain_invalidated_outputs"], 0)
        for name in ("build.ninja", "args.gn", ".ninja_deps", ".ninja_log"):
            self.assertTrue((self.out / name).exists())

    def test_inspect_wrong_host_is_successful_json_without_execution(self):
        self.fixture("macos", "x64", donor_arch="arm64")
        output = io.StringIO()
        with mock.patch.object(prepare, "host_identity", return_value=("macos", "x64")), \
                mock.patch.object(prepare.subprocess, "run") as run, redirect_stdout(output):
            code = prepare.main(["--phase", "inspect", "--platform", "macos", "--arch", "x64", "--workdir", str(self.work)])
        self.assertEqual(code, 0)
        self.assertFalse(json.loads(output.getvalue())["native_tools"])
        run.assert_not_called()
        self.assertTrue(json.loads((self.src / prepare.INSPECTION).read_text())["needs_invalidation"])

    def test_windows_is_not_executed_on_a_posix_host(self):
        self.fixture("windows", "x64")
        with mock.patch.object(prepare, "host_identity", return_value=("linux", "x64")), \
                mock.patch.object(prepare.subprocess, "run") as run:
            inspection = prepare.prepare(self.work, "windows", "x64", phase="inspect")
        self.assertFalse(inspection["native_tools"])
        run.assert_not_called()

    def test_windows_native_probe_uses_only_mocked_version_commands(self):
        self.fixture("windows", "x64")
        with self.native_context("windows", "x64"):
            result = prepare.prepare(self.work, "windows", "x64")
        self.assertTrue(result["native_tools"])

    def test_host_tool_failure_is_not_claimed_compatible(self):
        self.fixture("linux", "arm64")
        with mock.patch.object(prepare, "host_identity", return_value=("linux", "arm64")), \
                mock.patch.object(prepare.subprocess, "run", return_value=mock.Mock(returncode=1, stdout="GLIBC_2.38 not found")):
            result = prepare.validate_native_tools(self.src, "linux", "arm64")
        self.assertFalse(result["native_tools"])
        self.assertIn("GLIBC_2.38", result["tools"]["clang"]["version"])

    def test_unverified_source_fails_before_any_probe(self):
        with mock.patch.object(prepare.subprocess, "run") as run:
            with self.assertRaises((ValueError, OSError)):
                prepare.prepare(self.work, "linux", "x64", phase="inspect")
        run.assert_not_called()

    def test_resume_keeps_products_and_objects_until_environment_changes(self):
        self.fixture()
        internal = self.object("internal.o")
        self.object("external.o")
        self.deps({"obj/internal.o": ["../../include/a.h"], "obj/external.o": ["/unknown-sdk/header"]})
        with self.native_context():
            prepare.prepare(self.work, "macos", "arm64")
            external = self.object("external.o")
            product = self.write(self.out / "Chromium.app/Contents/MacOS/Chromium", "new product")
            result = prepare.prepare(self.work, "macos", "arm64")
            self.assertEqual(result["dependencies"]["removed_outputs"], 0)
            self.assertTrue(external.exists())
            with mock.patch.object(prepare, "environment_identity", return_value={"ImageVersion": "2", "SDK": "/sdk/27"}):
                result = prepare.prepare(self.work, "macos", "arm64")
        self.assertFalse(external.exists())
        self.assertTrue(internal.exists())
        self.assertTrue(product.exists())
        self.assertEqual(result["counters"]["environment_rechecks"], 1)
        self.assertEqual(result["counters"]["toolchain_invalidated_outputs"], 0)

    def test_host_swap_invalidates_compiled_and_host_binaries_but_not_sdk(self):
        self.fixture("macos", "x64", donor_arch="arm64")
        obj = self.object("internal.o")
        archive = self.object("rust.rlib")
        self.deps({"obj/internal.o": ["../../include/a.h"]})
        host_binary = self.out / "clang_arm64/mksnapshot"
        self.binary(host_binary, "macos", "arm64")
        sdk = self.write(self.out / "sdk/platform/lib.a", "SDK library")
        with self.native_context("macos", "x64"):
            prepare.prepare(self.work, "macos", "x64", phase="inspect")
            for name, relative in prepare.tool_paths("macos", "x64").items():
                if name != "gn":
                    self.binary(self.src / relative, "macos", "x64")
            result = prepare.prepare(self.work, "macos", "x64")
            self.assertGreaterEqual(result["counters"]["toolchain_invalidated_outputs"], 3)
            self.assertFalse(obj.exists())
            self.assertFalse(archive.exists())
            self.assertFalse(host_binary.exists())
            self.assertFalse((self.out / "gn").exists())
            self.assertTrue(sdk.exists())
            self.binary(self.out / "gn", "macos", "x64")
            obj = self.object("internal.o")
            result = prepare.prepare(self.work, "macos", "x64")
        self.assertTrue(obj.exists())
        self.assertEqual(result["counters"]["toolchain_invalidated_outputs"], 0)

    def test_repeated_inspect_cannot_hide_a_native_tool_replacement(self):
        self.fixture()
        obj = self.object("a.o")
        self.deps({"obj/a.o": ["../../include/a.h"]})
        with self.native_context():
            prepare.prepare(self.work, "macos", "arm64", phase="inspect")
            compiler = self.src / prepare.CLANG / "bin/clang"
            with compiler.open("ab") as stream:
                stream.write(b"new tool payload")
            again = prepare.prepare(self.work, "macos", "arm64", phase="inspect")
            self.assertTrue(again["needs_invalidation"])
            prepare.prepare(self.work, "macos", "arm64")
        self.assertFalse(obj.exists())

    def test_runtime_toolchain_content_change_not_just_version_invalidates(self):
        self.fixture()
        with self.native_context():
            prepare.prepare(self.work, "macos", "arm64")
            obj = self.object("a.o")
            self.deps({"obj/a.o": ["../../include/a.h"]})
            self.write(self.src / prepare.CLANG / "lib/libclang.dylib", "changed runtime")
            result = prepare.prepare(self.work, "macos", "arm64")
        self.assertFalse(obj.exists())
        self.assertEqual(result["counters"]["tool_swap_invalidations"], 1)

    def test_missing_node_link_does_not_discard_unrelated_compiled_objects(self):
        self.fixture("linux", "x64")
        obj = self.object("internal.o")
        node = self.src / prepare.tool_paths("linux", "x64")["node"]
        node.unlink()
        generated = self.write(self.out / "gen/node-output.h", "old generated")
        self.write(self.out / ".ninja_log", "# ninja log v5\n0\t1\t1\tgen/node-output.h\tabc\n")
        self.deps({"obj/internal.o": ["../../include/a.h"]})
        with self.native_context("linux", "x64"):
            inspection = prepare.prepare(self.work, "linux", "x64", phase="inspect")
            self.assertFalse(inspection["needs_invalidation"])
            self.binary(node, "linux", "x64")
            result = prepare.prepare(self.work, "linux", "x64")
        self.assertTrue(obj.exists())
        self.assertFalse(generated.exists())
        self.assertEqual(result["counters"]["toolchain_invalidated_outputs"], 0)
        self.assertEqual(result["generated_outputs"]["removed_outputs"], 1)

    def test_generator_content_change_rebuilds_generated_inputs_and_readers(self):
        self.fixture("linux", "x64")
        go = self.src / prepare.generator_paths("linux", "x64")["go"]
        self.write(go, "go version one")
        with self.native_context("linux", "x64"):
            prepare.prepare(self.work, "linux", "x64")
            independent = self.object("independent.o")
            dependent = self.object("generated.o")
            generated = self.write(self.out / "gen/go-output.h", "generated")
            self.deps({"obj/independent.o": ["../../include/a.h"],
                       "obj/generated.o": ["gen/go-output.h"]})
            self.write(self.out / ".ninja_log", "# ninja log v5\n0\t1\t1\tgen/go-output.h\tabc\n")
            self.write(go, "go version two")
            os.utime(go, ns=(1, 1))
            result = prepare.prepare(self.work, "linux", "x64")
        self.assertTrue(independent.exists())
        self.assertFalse(generated.exists())
        self.assertFalse(dependent.exists())
        self.assertEqual(result["counters"]["tool_swap_invalidations"], 0)
        self.assertEqual(result["counters"]["generator_rechecks"], 1)

    def test_arm64_repair_accepts_actual_eight_space_llvm_arguments(self):
        source = ("from build import GetHostSysrootPlatform, GitRevert\n"
                  "openssl = f'{OPENSSL_CIPD_LINUX_AMD_PATH}'\n"
                  "def triple():\n    return 'x86_64-unknown-linux-gnu'\n"
                  "def llvm():\n    flags = [\n        '--disable-asserts',\n        '--no-tools',\n    ]\n"
                  "    DownloadDebianSysroot('amd64', args.skip_checkout)\n")
        path = self.write(self.src / "tools/rust/build_rust.py", source)
        prepare.repair_linux_arm64_tool_script(self.src)
        changed = path.read_text()
        self.assertIn("        '--host-cc=clang',", changed)
        compile(changed, str(path), "exec")
        prepare.repair_linux_arm64_tool_script(self.src)
        self.assertEqual(changed, path.read_text())

    def test_linux_and_windows_relink_final_products(self):
        for platform, names in (("linux", ["chrome", "chrome_crashpad_handler", "chrome_sandbox"]),
                                ("windows", ["chrome.exe", "chrome.dll", "chrome_elf.dll"])):
            with self.subTest(platform=platform):
                for name in names:
                    self.write(self.out / name, "old binary")
                self.assertEqual(prepare.remove_final_products(self.src, platform), names)
                self.assertTrue((self.out / "obj").exists())

    def test_final_product_symlink_is_rejected(self):
        target = self.work / "user-app"
        target.mkdir()
        (self.out / "Chromium.app").symlink_to(target)
        with self.assertRaisesRegex(ValueError, "symlinked final"):
            prepare.remove_final_products(self.src, "macos")
        self.assertTrue(target.exists())

    def test_signed_bundle_internal_sdk_link_is_not_followed(self):
        sdk = self.write(self.work / "sdk/header", "SDK")
        self.write(self.out / "Chromium.app/Contents/_CodeSignature/CodeResources", "signed")
        (self.out / "Chromium.app/Contents/linked").symlink_to(sdk.parent)
        obj = self.object("a.o")
        prepare.remove_final_products(self.src, "macos")
        self.assertTrue(sdk.exists())
        self.assertTrue(obj.exists())

    def test_marker_symlink_cannot_overwrite_external_file(self):
        self.fixture()
        target = self.write(self.work / "keep", "keep")
        (self.src / prepare.MARKER).symlink_to(target)
        with self.assertRaisesRegex(ValueError, "unsafe"):
            prepare.prepare(self.work, "macos", "arm64")
        self.assertEqual(target.read_text(), "keep")

    def test_environment_records_runner_image_and_sdk_build_not_generated_graph(self):
        self.fixture()
        sdk = self.work / "SDK"
        self.write(sdk / "SDKSettings.json", '{"Version": "26.0"}')
        def run(command, **kwargs):
            values = {"--show-sdk-path": str(sdk), "--show-sdk-version": "26.0",
                      "--show-sdk-build-version": "25A", "-version": "Xcode 26\nBuild version 17A",
                      "--print-path": "/Applications/Xcode.app/Contents/Developer"}
            return mock.Mock(stdout=values[command[-1]], returncode=0)
        with mock.patch.dict(os.environ, {"ImageOS": "macos15", "ImageVersion": "v1", "GITHUB_JOB": "build-1"}), \
                mock.patch.object(prepare.subprocess, "run", side_effect=run):
            first = prepare.environment_identity(self.src, "macos")
            self.write(self.out / "build.ninja", "new graph")
            self.assertEqual(first, prepare.environment_identity(self.src, "macos"))
            with mock.patch.dict(os.environ, {"ImageVersion": "v2"}):
                self.assertNotEqual(first, prepare.environment_identity(self.src, "macos"))
        self.assertEqual(first["xcrun --sdk macosx --show-sdk-build-version"], "25A")
        self.assertEqual(first["sdks"][0]["root"]["path"], str(sdk))


if __name__ == "__main__":
    unittest.main()
