"""Tiny Mach-O fixtures and mocked Bash 3.2 builds; no downloads or compilation."""
import hashlib
import io
import json
import os
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path
import shutil
import struct
import subprocess
import sys
import tempfile
import unittest
from unittest import mock

from tools import macos_runtime as runtime

REPO = Path(__file__).resolve().parents[2]
BASH32 = Path.home() / ".local/bash-3.2-for-ci/bash"
PINNED_BINDGEN_WRAPPER = r'''#!/usr/bin/env python3

# Copyright 2022 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import argparse
import contextlib
import os
import subprocess
import sys

# Set up path to be able to import action_helpers.
sys.path.append(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir,
                 os.pardir, os.pardir, 'build'))
import action_helpers

from filter_clang_args import filter_clang_args


def PrependVersionLine(filepath):
  # Prepending a version line accomplishes two goals:
  # * P1: Incrementing the version forces reindexing of the generated code
  #   by Chromium Code Search (e.g. needed to verify the fix from
  #   https://crbug.com/466084840)
  # * P2: It leaves a breadcrumb about `//build/rust` to help readers of
  #   the generated code figure out where/how to control how Chromium
  #   invokes `bindgen`.
  VERSION = "2025-12-22"
  with open(filepath, 'r', encoding='utf-8') as f:
    original_content = f.read()
  with open(filepath, 'w', encoding='utf-8') as f:
    tool_description = f"`//build/rust/gni_impl/run_bindgen.py` v{VERSION}"
    f.write(f"/* @generated by {tool_description} */\n")
    f.write(original_content)


def main():
  parser = argparse.ArgumentParser("run_bindgen.py")
  parser.add_argument("--bindgen-exe", help="Path to bindgen", required=True),
  parser.add_argument("--rustfmt-exe", help="Path to rustfmt", required=True),
  parser.add_argument("--header",
                      help="C header file to generate bindings for",
                      required=True)
  parser.add_argument("--depfile",
                      help="depfile to output with header dependencies")
  parser.add_argument("--output", help="output .rs bindings", required=True)
  parser.add_argument(
      "--wrap-static-fns",
      help="output source file for `static` and `static inline` functions")
  parser.add_argument("--ld-library-path",
                      help="LD_LIBRARY_PATH (or DYLD_LIBRARY_PATH on Mac) to "
                      "set")
  parser.add_argument("--libclang-path",
                      help="Path to the libclang shared libray.")
  parser.add_argument("-I", "--include", help="include path", action="append")
  parser.add_argument("--bindgen-flags",
                      help="flags to pass to bindgen",
                      nargs="*")
  parser.add_argument(
      "clangargs",
      metavar="CLANGARGS",
      help="arguments to pass to libclang (see "
      "https://docs.rs/bindgen/latest/bindgen/struct.Builder.html#method.clang_args)",
      nargs="*")
  args = parser.parse_args()

  # Abort if `TARGET` exists in the environment. Cargo sets `TARGET` when
  # running build scripts and bindgen will try to be helpful by using that value
  # if it's set. In practice we've seen a case where someone had the value set
  # in their build environment with no intention of it reaching bindgen, leading
  # to a hard-to-debug build error.
  if 'TARGET' in os.environ:
    sys.exit('ERROR: saw TARGET in environment, remove to avoid bindgen'
             ' failures')

  with contextlib.ExitStack() as stack:
    # Args passed to the actual bindgen cli
    genargs = []
    genargs.append('--no-layout-tests')
    if args.bindgen_flags is not None:
      for flag in args.bindgen_flags:
        genargs.append("--" + flag)

    # TODO(danakj): We need to point bindgen to
    # //third_party/rust-toolchain/bin/rustfmt.
    genargs.append('--no-rustfmt-bindings')
    genargs += ['--rust-target', 'nightly']

    if args.depfile:
      depfile = stack.enter_context(action_helpers.atomic_output(args.depfile))
      genargs.append('--depfile')
      genargs.append(depfile.name)
    # Ideally we would use action_helpers.atomic_output for the output file, but
    # this would put the wrong name in the depfile.
    genargs.append('--output')
    genargs.append(args.output)

    # The GN rules know what path to find the system headers in, and we want to
    # use the headers we specify, instead of non-hermetic headers from elsewhere
    # in the system.
    genargs.append('--no-include-path-detection')

    if args.wrap_static_fns:
      wrap_static_fns = stack.enter_context(
          action_helpers.atomic_output(args.wrap_static_fns))
      genargs.append('--experimental')
      genargs.append('--wrap-static-fns')
      genargs.append('--wrap-static-fns-path')
      genargs.append(wrap_static_fns.name)
    genargs.append(args.header)
    genargs.append('--')
    genargs.extend(filter_clang_args(args.clangargs))
    env = os.environ
    if args.ld_library_path:
      if sys.platform == 'darwin':
        env["DYLD_LIBRARY_PATH"] = args.ld_library_path
      else:
        env["LD_LIBRARY_PATH"] = args.ld_library_path
    if args.libclang_path:
      env["LIBCLANG_PATH"] = args.libclang_path
    try:
      subprocess.check_call([args.bindgen_exe, *genargs], env=env)

      fmtargs = [
          args.output,
          "--config=normalize_doc_attributes=true",
      ]
      subprocess.check_call([args.rustfmt_exe, *fmtargs])

      PrependVersionLine(args.output)
    except:
      # Make sure we don't emit anything if bindgen failed. The other files use
      # action_helpers for this.
      try:
        os.remove(args.output)
      except FileNotFoundError:
        pass
      raise


if __name__ == '__main__':
  main()
'''


def wrapper_fixture(src):
    data = PINNED_BINDGEN_WRAPPER.encode()
    assert hashlib.sha256(data).hexdigest() == runtime.BINDGEN_ORIGINAL_SHA256
    path = src / runtime.BINDGEN_WRAPPER
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return path


def binary(path, arch="arm64"):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(struct.pack("<8I", 0xFEEDFACF, runtime.CPUS[arch], 0, 6, 0, 0, 0, 0))
    return path


def layout(src, arch="arm64"):
    for directory in runtime.LIBRARY_DIRS[:2]:
        binary(src / directory / "libclang.dylib", arch)
    rustc = src / "third_party/rust-toolchain/rustc"
    binary(rustc / "lib/libLLVM.dylib", arch)
    binary(rustc / f"lib/rustlib/{runtime.TRIPLES[arch]}/bin/rust-objcopy", arch).chmod(0o755)
    std = src / f"third_party/rust-toolchain/rust-std-{runtime.TRIPLES[arch]}"
    stdlib = std / f"lib/rustlib/{runtime.TRIPLES[arch]}/lib"
    stdlib.mkdir(parents=True)
    (rustc / f"lib/rustlib/{runtime.TRIPLES[arch]}/lib").symlink_to(stdlib)
    return stdlib / "libLLVM.dylib"


class MacOSRuntimeTest(unittest.TestCase):
    def setUp(self):
        temp = tempfile.TemporaryDirectory(prefix="mac runtime ' ")
        self.addCleanup(temp.cleanup)
        self.root = Path(temp.name)
        self.src = self.root / "src"
        self.src.mkdir()

    def test_default_environment_scrubs_all_dyld_without_mutation(self):
        for arch in runtime.TRIPLES:
            with self.subTest(arch=arch):
                src = self.src / arch
                src.mkdir()
                destination = layout(src, arch)
                original = {"PATH": "kept", "DYLD_LIBRARY_PATH": ":/usr/local/lib:/donor/lib:",
                            "DYLD_FALLBACK_LIBRARY_PATH": "/external", "DYLD_FRAMEWORK_PATH": "/frameworks",
                            "DYLD_INSERT_LIBRARIES": "/injected.dylib", "DYLD_VERSIONED_LIBRARY_PATH": "/versions",
                            "DYLD_UNKNOWN_OVERRIDE": "/bad"}
                with mock.patch.object(subprocess, "run", side_effect=AssertionError("no execution")):
                    env = runtime.runtime_environment(src, arch, original)
                self.assertEqual(env, {"PATH": "kept"})
                self.assertEqual(original["DYLD_LIBRARY_PATH"], ":/usr/local/lib:/donor/lib:")
                self.assertFalse(destination.exists())
                self.assertEqual(runtime.runtime_environment(src, arch, env), env)

    def test_bindgen_view_prefers_rust_libclang_without_exposing_other_libraries(self):
        for arch in runtime.TRIPLES:
            with self.subTest(arch=arch):
                src = self.src / arch
                src.mkdir()
                layout(src, arch)
                rust = src / runtime.LIBRARY_DIRS[1] / "libclang.dylib"
                for directory in runtime.LIBRARY_DIRS:
                    binary(src / directory / "libc++abi.dylib", arch)
                before = {path: (path.read_bytes(), path.stat().st_mtime_ns)
                          for path in src.rglob("*") if path.is_file()}
                original = {"PATH": "kept", "DYLD_LIBRARY_PATH": "/bad", "DYLD_INSERT_LIBRARIES": "/bad"}
                with mock.patch.object(subprocess, "run", side_effect=AssertionError("no execution")), \
                        runtime.bindgen_environment(src, arch, original) as env:
                    view = Path(env["DYLD_LIBRARY_PATH"])
                    self.assertEqual(env, {"PATH": "kept", "DYLD_LIBRARY_PATH": str(view)})
                    self.assertEqual([p.name for p in view.iterdir()], ["libclang.dylib"])
                    self.assertTrue((view / "libclang.dylib").is_symlink())
                    self.assertEqual((view / "libclang.dylib").resolve(), rust)
                    self.assertFalse(view.is_relative_to(src))
                self.assertFalse(view.exists())
                self.assertEqual(original["DYLD_LIBRARY_PATH"], "/bad")
                self.assertEqual(before, {path: (path.read_bytes(), path.stat().st_mtime_ns) for path in before})

    def test_absent_foreign_or_malformed_libclang_yields_clean_environment(self):
        directory = self.src / runtime.LIBRARY_DIRS[1]
        library = directory / "libclang.dylib"
        for data in (None, b"not a Mach-O", struct.pack("<II", 0xFEEDFACF, runtime.CPUS["x64"])):
            if data is not None:
                directory.mkdir(parents=True, exist_ok=True)
                library.write_bytes(data)
            with runtime.bindgen_environment(self.src, "arm64", {"PATH": "kept", "DYLD_LIBRARY_PATH": "."}) as env:
                self.assertEqual(env, {"PATH": "kept"})
        fallback = binary(self.src / runtime.LIBRARY_DIRS[0] / "libclang.dylib")
        (fallback.parent / "libbroken.dylib").symlink_to("missing")
        with runtime.bindgen_environment(self.src, "arm64", {}) as env:
            view = Path(env["DYLD_LIBRARY_PATH"])
            self.assertEqual((view / "libclang.dylib").resolve(), fallback)
            self.assertEqual([p.name for p in view.iterdir()], ["libclang.dylib"])
        self.assertFalse(view.exists())

    def test_bindgen_view_is_removed_on_child_failure(self):
        binary(self.src / runtime.LIBRARY_DIRS[0] / "libclang.dylib")
        with self.assertRaisesRegex(RuntimeError, "probe failed"):
            with runtime.bindgen_environment(self.src, "arm64", {}) as env:
                view = Path(env["DYLD_LIBRARY_PATH"])
                raise RuntimeError("probe failed")
        self.assertFalse(view.exists())

    def test_fat_architectures_are_checked_without_executing(self):
        library = binary(self.src / runtime.LIBRARY_DIRS[0] / "libclang.dylib")
        for magic, width in ((0xCAFEBABE, 20), (0xCAFEBABF, 32)):
            data = struct.pack(">II", magic, 2)
            data += b"".join(struct.pack(">I", cpu) + b"\0" * (width - 4) for cpu in runtime.CPUS.values())
            library.write_bytes(data)
            for arch in runtime.TRIPLES:
                with runtime.bindgen_environment(self.src, arch, {}) as env:
                    self.assertEqual((Path(env["DYLD_LIBRARY_PATH"]) / "libclang.dylib").resolve(), library)
            library.write_bytes(data[:-1])
            with runtime.bindgen_environment(self.src, "arm64", {}) as env:
                self.assertEqual(env, {})
        library.write_bytes(struct.pack(">II", 0xCAFEBABE, 33))
        with runtime.bindgen_environment(self.src, "arm64", {}) as env:
            self.assertEqual(env, {})

    def test_runtime_root_and_architecture_validation(self):
        for name in ("bad:root", "bad\nroot", "bad\rroot"):
            src = self.root / name
            src.mkdir()
            with self.assertRaisesRegex(ValueError, "unsafe"):
                runtime.runtime_environment(src, "arm64", {})
        alias = self.root / "alias"
        alias.symlink_to(self.src)
        with self.assertRaisesRegex(ValueError, "linked"):
            runtime.runtime_environment(alias, "arm64", {})
        with self.assertRaisesRegex(ValueError, "architecture"):
            runtime.runtime_environment(self.src, "../../x64", {})

    def test_directory_and_dylib_symlink_escapes_are_rejected(self):
        outside = self.root / "outside"
        binary(outside / "libclang.dylib")
        directory = self.src / runtime.LIBRARY_DIRS[0]
        directory.parent.mkdir(parents=True)
        directory.symlink_to(outside)
        with self.assertRaisesRegex(ValueError, "escapes source"), \
                runtime.bindgen_environment(self.src, "arm64", {}):
            self.fail("linked directory accepted")
        directory.unlink()
        directory.mkdir()
        (directory / "libclang.dylib").symlink_to(outside / "libclang.dylib")
        with self.assertRaisesRegex(ValueError, "escapes source"), \
                runtime.bindgen_environment(self.src, "arm64", {}):
            self.fail("linked library accepted")
        self.assertEqual(runtime.runtime_environment(self.src, "arm64", {}), {})

    def test_internal_library_links_are_resolved(self):
        directory = self.src / runtime.LIBRARY_DIRS[0]
        library = binary(directory / "libclang.23.dylib")
        (directory / "libclang.dylib").symlink_to("libclang.23.dylib")
        rustlib = self.src / runtime.LIBRARY_DIRS[1]
        rustlib.parent.mkdir(parents=True)
        rustlib.symlink_to(directory)
        with runtime.bindgen_environment(self.src, "arm64", {}) as env:
            view = Path(env["DYLD_LIBRARY_PATH"])
            self.assertEqual((view / "libclang.dylib").resolve(), library)
        self.assertFalse(view.exists())

    def test_loader_link_is_relative_idempotent_and_preserves_binary_bytes(self):
        for arch in runtime.TRIPLES:
            with self.subTest(arch=arch):
                src = self.src / arch
                src.mkdir()
                destination = layout(src, arch)
                files = {path: (path.read_bytes(), path.stat().st_mtime_ns)
                         for path in src.rglob("*") if path.is_file()}
                runtime.prepare_runtime_loader(src, arch)
                self.assertTrue(destination.is_symlink())
                self.assertFalse(Path(os.readlink(destination)).is_absolute())
                self.assertEqual(destination.resolve(), src / runtime.LIBRARY_DIRS[2] / "libLLVM.dylib")
                before = destination.lstat().st_mtime_ns
                runtime.prepare_runtime_loader(src, arch)
                self.assertEqual(destination.lstat().st_mtime_ns, before)
                self.assertEqual(files, {path: (path.read_bytes(), path.stat().st_mtime_ns) for path in files})

    def test_missing_or_wrong_architecture_objcopy_fails_without_a_loader_link(self):
        destination = layout(self.src, "arm64")
        with self.assertRaisesRegex(ValueError, "missing or non-native"):
            runtime.prepare_runtime_loader(self.src, "x64")
        self.assertFalse(destination.exists())
        objcopy = self.src / "third_party/rust-toolchain/rustc/lib/rustlib/aarch64-apple-darwin/bin/rust-objcopy"
        binary(objcopy, "x64")
        with self.assertRaisesRegex(ValueError, "missing or non-native"):
            runtime.prepare_runtime_loader(self.src, "arm64")
        self.assertFalse(destination.exists())
        objcopy.unlink()
        with self.assertRaisesRegex(ValueError, "missing or non-native"):
            runtime.prepare_runtime_loader(self.src, "arm64")
        self.assertFalse(destination.exists())

    def test_missing_foreign_llvm_and_missing_directory_fail_without_repair(self):
        destination = layout(self.src)
        library = self.src / runtime.LIBRARY_DIRS[2] / "libLLVM.dylib"
        binary(library, "x64")
        with self.assertRaisesRegex(ValueError, "missing or non-native"):
            runtime.prepare_runtime_loader(self.src, "arm64")
        self.assertFalse(destination.exists())
        library.unlink()
        with self.assertRaisesRegex(ValueError, "missing or non-native"):
            runtime.prepare_runtime_loader(self.src, "arm64")
        self.assertFalse(destination.exists())
        binary(library)
        destination.parent.rmdir()
        with self.assertRaisesRegex(ValueError, "missing nightly Rust runtime library directory"):
            runtime.prepare_runtime_loader(self.src, "arm64")
        self.assertFalse(destination.exists())

    def test_loader_destination_escape_is_rejected_without_writing(self):
        destination = layout(self.src)
        outside = self.root / "external lib"
        outside.mkdir()
        destination.symlink_to(outside / "libLLVM.dylib")
        with self.assertRaisesRegex(ValueError, "escapes source"):
            runtime.prepare_runtime_loader(self.src, "arm64")
        self.assertEqual(list(outside.iterdir()), [])
        self.assertTrue(destination.is_symlink())

    def test_loader_keeps_valid_existing_library_and_rejects_foreign_one(self):
        destination = layout(self.src)
        binary(destination)
        before = destination.stat().st_mtime_ns
        runtime.prepare_runtime_loader(self.src, "arm64")
        self.assertFalse(destination.is_symlink())
        self.assertEqual(destination.stat().st_mtime_ns, before)
        binary(destination, "x64")
        with self.assertRaisesRegex(ValueError, "invalid existing"):
            runtime.prepare_runtime_loader(self.src, "arm64")

    def test_wrapper_fixture_matches_actual_pinned_upstream(self):
        upstream = REPO / ".chromix-build-mac-verify/src" / runtime.BINDGEN_WRAPPER
        if not upstream.is_file():
            self.skipTest("local pinned Chromium wrapper required")
        self.assertEqual(upstream.read_bytes(), PINNED_BINDGEN_WRAPPER.encode())

    def test_wrapper_repair_is_strict_and_idempotent(self):
        path = wrapper_fixture(self.src)
        path.chmod(0o755)
        runtime.repair_bindgen_wrapper(self.src, "arm64")
        patched = path.read_bytes()
        self.assertEqual(hashlib.sha256(patched).hexdigest(), runtime.BINDGEN_PATCHED_SHA256)
        self.assertEqual(patched.count(b"import tempfile\n"), 1)
        self.assertEqual(patched.count(runtime.BINDGEN_SCOPED_ENV), 1)
        self.assertTrue(os.access(path, os.X_OK))
        before = path.stat().st_mtime_ns
        runtime.repair_bindgen_wrapper(self.src, "x64")
        self.assertEqual(path.stat().st_mtime_ns, before)
        for drift in (PINNED_BINDGEN_WRAPPER.encode() + b"# drift\n", patched + b"# drift\n", b"unknown"):
            path.write_bytes(drift)
            with self.assertRaisesRegex(ValueError, "unknown bindgen wrapper SHA256"):
                runtime.repair_bindgen_wrapper(self.src, "arm64")
            self.assertEqual(path.read_bytes(), drift)

    def test_wrapper_repair_rejects_linked_file_and_parent_without_writing(self):
        path = wrapper_fixture(self.src)
        outside = self.root / "external.py"
        path.rename(outside)
        path.symlink_to(outside)
        with self.assertRaisesRegex(ValueError, "escapes source"):
            runtime.repair_bindgen_wrapper(self.src, "arm64")
        path.unlink()
        directory = self.root / "external-directory"
        path.parent.rename(directory)
        path.parent.symlink_to(directory, target_is_directory=True)
        (directory / path.name).write_bytes(PINNED_BINDGEN_WRAPPER.encode())
        with self.assertRaisesRegex(ValueError, "escapes source"):
            runtime.repair_bindgen_wrapper(self.src, "arm64")
        self.assertEqual(outside.read_bytes(), PINNED_BINDGEN_WRAPPER.encode())
        self.assertEqual((directory / path.name).read_bytes(), PINNED_BINDGEN_WRAPPER.encode())

    def load_wrapper(self):
        import importlib.util
        import types
        path = wrapper_fixture(self.src)
        runtime.repair_bindgen_wrapper(self.src, "arm64")
        action_helpers = types.ModuleType("action_helpers")
        filter_args = types.ModuleType("filter_clang_args")
        filter_args.filter_clang_args = lambda values: values
        spec = importlib.util.spec_from_file_location("pinned_run_bindgen", path)
        module = importlib.util.module_from_spec(spec)
        with mock.patch.dict(sys.modules, action_helpers=action_helpers, filter_clang_args=filter_args), \
                mock.patch.object(sys, "path", list(sys.path)):
            spec.loader.exec_module(module)
        return module

    def test_actual_wrapper_scopes_libclang_and_never_mutates_rustfmt_environment(self):
        module = self.load_wrapper()
        layout(self.src)
        library = self.src / runtime.LIBRARY_DIRS[0]
        binary(library / "libc++abi.dylib")
        output = self.root / "bindings.rs"
        for inherited in ({}, {"PATH": "/kept", "DYLD_LIBRARY_PATH": "/bad", "DYLD_INSERT_LIBRARIES": "/bad",
                               "DYLD_UNKNOWN_OVERRIDE": "/bad"}):
            with self.subTest(inherited=inherited):
                output.write_text("// mocked bindings\n")
                calls, views = [], []
                def check_call(command, **kwargs):
                    env = dict(kwargs.get("env", os.environ))
                    calls.append((command, env))
                    self.assertEqual(dict(os.environ), inherited)
                    if command[0] == "bindgen":
                        view = Path(env["DYLD_LIBRARY_PATH"])
                        views.append(view)
                        self.assertEqual([p.name for p in view.iterdir()], ["libclang.dylib"])
                        self.assertTrue((view / "libclang.dylib").is_symlink())
                        self.assertEqual((view / "libclang.dylib").resolve(), library / "libclang.dylib")
                        self.assertEqual(env["LIBCLANG_PATH"], str(library))
                        self.assertEqual([key for key in env if key.startswith("DYLD_")], ["DYLD_LIBRARY_PATH"])
                    else:
                        self.assertEqual(env, inherited)
                        self.assertNotIn("env", kwargs)
                argv = [module.__file__, "--bindgen-exe", "bindgen", "--rustfmt-exe", "rustfmt",
                        "--header", "input.h", "--output", str(output),
                        "--ld-library-path", str(library), "--libclang-path", str(library)]
                with mock.patch.dict(os.environ, inherited, clear=True), mock.patch.object(sys, "platform", "darwin"), \
                        mock.patch.object(sys, "argv", argv), \
                        mock.patch.object(module.subprocess, "check_call", side_effect=check_call):
                    module.main()
                self.assertEqual([command[0] for command, _ in calls], ["bindgen", "rustfmt"])
                self.assertEqual(len(views), 1)
                self.assertFalse(views[0].exists())
                self.assertTrue(output.read_text().startswith("/* @generated by"))

    def test_wrapper_view_and_output_are_removed_on_bindgen_failure(self):
        module = self.load_wrapper()
        library = binary(self.src / runtime.LIBRARY_DIRS[0] / "libclang.dylib").parent
        output = self.root / "bindings.rs"
        output.write_text("incomplete")
        views = []
        def check_call(command, **kwargs):
            view = Path(kwargs["env"]["DYLD_LIBRARY_PATH"])
            self.assertTrue((view / "libclang.dylib").is_file())
            views.append(view)
            raise subprocess.CalledProcessError(-6, command)
        argv = [module.__file__, "--bindgen-exe", "bindgen", "--rustfmt-exe", "rustfmt",
                "--header", "input.h", "--output", str(output), "--ld-library-path", str(library)]
        with mock.patch.dict(os.environ, {}, clear=True), mock.patch.object(sys, "platform", "darwin"), \
                mock.patch.object(sys, "argv", argv), \
                mock.patch.object(module.subprocess, "check_call", side_effect=check_call) as child:
            with self.assertRaises(subprocess.CalledProcessError):
                module.main()
        self.assertEqual(child.call_count, 1)
        self.assertFalse(output.exists())
        self.assertFalse(views[0].exists())

    def test_wrapper_without_loader_path_and_non_darwin_behavior(self):
        module = self.load_wrapper()
        output = self.root / "bindings.rs"
        inherited = {"PATH": "kept", "DYLD_LIBRARY_PATH": "/inherited", "DYLD_INSERT_LIBRARIES": "/inherited"}
        for platform, flags in (("darwin", []), ("linux", ["--ld-library-path", "llvm/lib"]),
                                ("win32", ["--ld-library-path", "llvm/lib"])):
            with self.subTest(platform=platform):
                output.write_text("// bindings\n")
                argv = [module.__file__, "--bindgen-exe", "bindgen", "--rustfmt-exe", "rustfmt",
                        "--header", "input.h", "--output", str(output), *flags]
                with mock.patch.dict(os.environ, inherited, clear=True), mock.patch.object(sys, "platform", platform), \
                        mock.patch.object(sys, "argv", argv), mock.patch.object(module.tempfile, "TemporaryDirectory") as temp, \
                        mock.patch.object(module.subprocess, "check_call") as child:
                    module.main()
                    self.assertEqual(dict(os.environ), inherited)
                expected = {"PATH": "kept"} if platform == "darwin" else dict(inherited, LD_LIBRARY_PATH="llvm/lib")
                self.assertEqual(child.call_args_list[0].kwargs["env"], expected)
                self.assertEqual(child.call_args_list[1].kwargs, {})
                temp.assert_not_called()

    def test_read_only_probe_environment_and_loader_fix_preserve_compiler_objects(self):
        from tools import prepare_restored_build as prepare
        from tools.tests.test_prepare_restored_build import PrepareRestoredBuildTest
        fixture = PrepareRestoredBuildTest()
        fixture.setUp()
        self.addCleanup(fixture.doCleanups)
        fixture.fixture()
        layout(fixture.src)
        output = fixture.object("keep.o")
        fixture.deps({"obj/keep.o": ["../../include/a.h"]})
        before = output.stat().st_mtime_ns
        wrapper = wrapper_fixture(fixture.src)
        views = []
        inherited = {"DYLD_LIBRARY_PATH": "/poisoned", "DYLD_UNKNOWN_OVERRIDE": "/bad"}
        def run(command, **kwargs):
            env = kwargs["env"]
            if Path(command[0]).name == "bindgen":
                view = Path(env["DYLD_LIBRARY_PATH"])
                views.append(view)
                self.assertEqual([p.name for p in view.iterdir()], ["libclang.dylib"])
                self.assertEqual((view / "libclang.dylib").resolve(),
                                 fixture.src / runtime.LIBRARY_DIRS[1] / "libclang.dylib")
                self.assertEqual(env, {"DYLD_LIBRARY_PATH": str(view)})
            else:
                self.assertEqual(env, {})
            return mock.Mock(returncode=0, stdout="native tool")
        with fixture.native_context(), mock.patch.dict(os.environ, inherited, clear=True), \
                mock.patch.object(prepare.subprocess, "run", side_effect=run):
            initial = prepare.prepare(fixture.work, "macos", "arm64", phase="inspect")
            runtime.prepare_runtime_loader(fixture.src, "arm64")
            runtime.repair_bindgen_wrapper(fixture.src, "arm64")
            finished = prepare.prepare(fixture.work, "macos", "arm64")
            resumed = prepare.prepare(fixture.work, "macos", "arm64")
        self.assertEqual(hashlib.sha256(wrapper.read_bytes()).hexdigest(), runtime.BINDGEN_PATCHED_SHA256)
        self.assertEqual(len(views), 3)
        self.assertTrue(all(not view.exists() for view in views))
        self.assertFalse(initial["needs_invalidation"])
        self.assertEqual(output.stat().st_mtime_ns, before)
        for result in (finished, resumed):
            self.assertEqual(result["counters"]["tool_swap_invalidations"], 0)
            self.assertEqual(result["counters"]["toolchain_invalidated_outputs"], 0)

    def test_missing_libclang_keeps_real_bindgen_probe_failure(self):
        from tools import prepare_restored_build as prepare
        from tools.tests.test_prepare_restored_build import PrepareRestoredBuildTest
        fixture = PrepareRestoredBuildTest()
        fixture.setUp()
        self.addCleanup(fixture.doCleanups)
        fixture.fixture()
        def run(command, **kwargs):
            self.assertEqual(kwargs["env"], {})
            failed = Path(command[0]).name == "bindgen"
            return mock.Mock(returncode=-6 if failed else 0,
                             stdout="dyld: Library not loaded: @rpath/libclang.dylib" if failed else "native")
        with fixture.native_context(), mock.patch.dict(os.environ, {"DYLD_LIBRARY_PATH": "/bad"}, clear=True), \
                mock.patch.object(prepare.subprocess, "run", side_effect=run) as probe:
            result = prepare.inspect_native_tools(fixture.src, "macos", "arm64")
        self.assertEqual(probe.call_count, len(prepare.tool_paths("macos", "arm64")))
        self.assertFalse(result["native_tools"])
        self.assertTrue(result["compilers_native"])
        self.assertFalse(result["tools"]["bindgen"]["native"])
        self.assertIn("--version exited -6", result["tools"]["bindgen"]["reason"])
        self.assertIn("libclang.dylib", result["tools"]["bindgen"]["version"])

    def test_native_post_link_probe_for_both_architectures_has_no_dyld_overrides(self):
        for arch in runtime.TRIPLES:
            with self.subTest(arch=arch):
                src = self.src / arch
                src.mkdir()
                layout(src, arch)
                runtime.prepare_runtime_loader(src, arch)
                objcopy = src / f"third_party/rust-toolchain/rustc/lib/rustlib/{runtime.TRIPLES[arch]}/bin/rust-objcopy"
                inherited = {"PATH": "/kept", "DYLD_LIBRARY_PATH": "/bad", "DYLD_INSERT_LIBRARIES": "/bad",
                             "DYLD_FALLBACK_LIBRARY_PATH": "/bad", "DYLD_UNKNOWN_OVERRIDE": "/bad"}
                stdout, stderr = io.StringIO(), io.StringIO()
                with mock.patch.object(runtime.platform, "system", return_value="Darwin"), \
                        mock.patch.object(runtime.platform, "machine", return_value="arm64" if arch == "arm64" else "x86_64"), \
                        mock.patch.dict(os.environ, inherited, clear=True), \
                        mock.patch.object(runtime.subprocess, "run", return_value=mock.Mock(
                            returncode=0, stdout="LLVM version 23\n" + "x" * 4000)) as run, \
                        redirect_stdout(stdout), redirect_stderr(stderr):
                    status = runtime.main(["--src", str(src), "--arch", arch, "--verify-loader"])
                self.assertEqual(status, 0, stderr.getvalue())
                run.assert_called_once_with([str(objcopy), "--version"], cwd=src, env={"PATH": "/kept"},
                                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                            text=True, errors="replace", timeout=10, check=False)
                self.assertIn("LLVM version 23", stderr.getvalue())
                self.assertLess(len(stderr.getvalue()), 2200)
                self.assertEqual(stdout.getvalue(), 'unset -- "${!DYLD_@}"\n')
                self.assertNotIn("LLVM version", stdout.getvalue())

    def test_probe_failure_and_timeout_fail_cli_with_bounded_stderr_only(self):
        layout(self.src)
        runtime.prepare_runtime_loader(self.src, "arm64")
        for timeout in (False, True):
            with self.subTest(timeout=timeout):
                stdout, stderr = io.StringIO(), io.StringIO()
                kwargs = {"side_effect": subprocess.TimeoutExpired("rust-objcopy", 10, output=b"dyld: " + b"x" * 5000)} if timeout else {
                    "return_value": mock.Mock(returncode=-6, stdout="dyld: " + "x" * 5000)}
                with mock.patch.object(runtime.platform, "system", return_value="Darwin"), \
                        mock.patch.object(runtime.platform, "machine", return_value="arm64"), \
                        mock.patch.object(runtime.subprocess, "run", **kwargs) as run, \
                        redirect_stdout(stdout), redirect_stderr(stderr):
                    status = runtime.main(["--src", str(self.src), "--arch", "arm64", "--verify-loader"])
                self.assertEqual(status, 1)
                run.assert_called_once()
                self.assertEqual(stdout.getvalue(), "")
                self.assertIn("dyld:", stderr.getvalue())
                self.assertIn("timed out after 10 seconds" if timeout else "exited -6", stderr.getvalue())
                self.assertLess(len(stderr.getvalue()), 2400)

    def test_probe_requires_native_host_before_execution(self):
        layout(self.src)
        runtime.prepare_runtime_loader(self.src, "arm64")
        for system, machine in (("Linux", "arm64"), ("Darwin", "x86_64"), ("Darwin", "unknown")):
            with self.subTest(system=system, machine=machine), \
                    mock.patch.object(runtime.platform, "system", return_value=system), \
                    mock.patch.object(runtime.platform, "machine", return_value=machine), \
                    mock.patch.object(runtime.subprocess, "run") as run:
                with self.assertRaisesRegex(ValueError, "native macOS arm64 host"):
                    runtime.verify_runtime_loader(self.src, "arm64")
                run.assert_not_called()

    def test_probe_rejects_missing_link_foreign_headers_and_unexecutable_objcopy(self):
        destination = layout(self.src)
        objcopy = self.src / "third_party/rust-toolchain/rustc/lib/rustlib/aarch64-apple-darwin/bin/rust-objcopy"
        library = self.src / runtime.LIBRARY_DIRS[2] / "libLLVM.dylib"
        with mock.patch.object(runtime.platform, "system", return_value="Darwin"), \
                mock.patch.object(runtime.platform, "machine", return_value="arm64"), \
                mock.patch.object(runtime.subprocess, "run") as run:
            with self.assertRaisesRegex(ValueError, "repaired Rust LLVM runtime"):
                runtime.verify_runtime_loader(self.src, "arm64")
            self.assertFalse(destination.exists())
            runtime.prepare_runtime_loader(self.src, "arm64")
            for path in (objcopy, library):
                binary(path, "x64")
                with self.assertRaisesRegex(ValueError, "missing or non-native"):
                    runtime.verify_runtime_loader(self.src, "arm64")
                binary(path)
            objcopy.chmod(0o644)
            with self.assertRaisesRegex(ValueError, "not executable"):
                runtime.verify_runtime_loader(self.src, "arm64")
            run.assert_not_called()

    def test_read_only_cli_and_prepare_loader_never_probe(self):
        destination = layout(self.src)
        for flags in ([], ["--prepare-loader"]):
            stdout = io.StringIO()
            with mock.patch.object(runtime.subprocess, "run") as run, redirect_stdout(stdout):
                status = runtime.main(["--src", str(self.src), "--arch", "arm64", *flags])
            self.assertEqual(status, 0)
            run.assert_not_called()
            self.assertEqual(destination.exists(), bool(flags))

    def test_cli_failure_emits_no_shell_code(self):
        result = subprocess.run([sys.executable, str(REPO / "tools/macos_runtime.py"),
                                 "--src", str(self.src / "absent"), "--arch", "arm64"],
                                text=True, capture_output=True, timeout=10)
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(result.stdout, "")


MOCK_COMMAND = r'''
import json, os, sys
from pathlib import Path
name = Path(sys.argv[0]).name
args = sys.argv[1:]
if name == "uname":
    assert not any(key.startswith("DYLD_") for key in os.environ)
    print(os.environ["MACHINE"] if args == ["-m"] else "Darwin")
    raise SystemExit(0)
if name == "python3" and args[0] == "-c":
    os.execv(sys.executable, [sys.executable] + args)
if name == "python3" and Path(args[0]).name == "macos_runtime.py":
    if "--verify-loader" in args:
        import importlib.util
        from unittest import mock
        spec = importlib.util.spec_from_file_location("mocked_runtime", args[0])
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        def probe(command, **kwargs):
            assert command[1:] == ["--version"] and Path(command[0]).name == "rust-objcopy"
            assert kwargs["timeout"] == 10 and not any(key.startswith("DYLD_") for key in kwargs["env"])
            assert Path(os.environ["LOADER_LINK"]).is_file()
            with Path(os.environ["CALL_LOG"]).open("a") as stream:
                stream.write(json.dumps(["verify-loader", args, {
                    key: value for key, value in os.environ.items() if key.startswith("DYLD_")}]) + "\n")
            return mock.Mock(returncode=-6 if os.environ.get("FAIL_LOADER_PROBE") else 0, stdout="mocked LLVM version")
        with mock.patch.object(module.platform, "system", return_value="Darwin"), \
                mock.patch.object(module.platform, "machine", return_value=os.environ["MACHINE"]), \
                mock.patch.object(module.subprocess, "run", side_effect=probe):
            raise SystemExit(module.main(args[1:]))
    os.execv(sys.executable, [sys.executable] + args)
if name == "python3" and Path(args[0]).name == "bootstrap_gn.py":
    assert not any(key.startswith("DYLD_") for key in os.environ)
    os.execv(sys.executable, [sys.executable] + args)
if name == "python3":
    name = Path(args[0]).name
dyld = {key: value for key, value in os.environ.items() if key.startswith("DYLD_")}
with Path(os.environ["CALL_LOG"]).open("a") as stream:
    stream.write(json.dumps([name, args, dyld]) + "\n")
if dyld:
    raise SystemExit("tool inherited DYLD overrides: " + name)
if name == "prepare_restored_build.py":
    phase = args[args.index("--phase") + 1]
    if phase == "inspect":
        print(json.dumps({"compilers_native": os.environ.get("RETRIEVE_RUNTIME") != "1", "tools": {
            "bindgen": {"native": os.environ.get("REBUILD_BINDGEN") != "1"},
            "node": {"native": True}}}))
    else:
        destination = Path(os.environ["LOADER_LINK"])
        if not destination.is_file():
            raise SystemExit("finish lacks the Rust LLVM loader link")
        import hashlib
        if hashlib.sha256(Path(os.environ["BINDGEN_WRAPPER"]).read_bytes()).hexdigest() != os.environ["WRAPPER_SHA256"]:
            raise SystemExit("finish lacks the scoped bindgen wrapper")
        print('{"ready_for_gn": true}')
elif name == "retrieve_and_unpack_resource.py":
    if os.environ.get("RETRIEVE_RUNTIME") != "1":
        raise SystemExit("unexpected resource retrieval")
    import struct
    library = Path(os.environ["LLVM_RUNTIME"])
    library.write_bytes(struct.pack("<8I", 0xFEEDFACF, 0x1000007, 0, 6, 0, 0, 0, 0))
elif name == "build_bindgen.py":
    if os.environ.get("REBUILD_BINDGEN") != "1":
        raise SystemExit("unexpected bindgen rebuild")
    if not Path(os.environ["LOADER_LINK"]).is_file():
        raise SystemExit("bindgen build lacks loader link")
elif name == "-":
    pass
elif name not in ("prepare-ungoogled.sh", "gn", "ninja", "merge_gn_args.py"):
    raise SystemExit("unexpected command; no downloads/builds: " + name)
'''


class MacOSRuntimeShellTest(unittest.TestCase):
    SHELL = shutil.which("bash")

    def setUp(self):
        temp = tempfile.TemporaryDirectory(prefix="mac shell ' ")
        self.addCleanup(temp.cleanup)
        self.root = Path(temp.name)
        self.repo = self.root / "repo"
        self.work = self.root / "work"
        self.src = self.work / "src"
        self.src.mkdir(parents=True)
        self.bin = self.root / "bin"
        self.bin.mkdir()
        self.log = self.root / "calls.jsonl"
        for relative in ("build/macos/build.sh", "build/posix/prepare-restored-tools.sh",
                         "tools/macos_runtime.py", "tools/bootstrap_gn.py"):
            target = self.repo / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(REPO / relative, target)
        self.executable(self.bin / "uname")
        (self.bin / "bash").symlink_to(self.SHELL)
        self.executable(self.bin / "python3")
        self.executable(self.bin / "ninja")
        self.executable(self.repo / "build/prepare-ungoogled.sh")
        (self.repo / "build/macos/select-xcode.sh").write_text("select_macos_xcode() { :; }\n")
        (self.repo / "build/posix/upstream-cache.sh").write_text(
            'chromix_select_restored_ninja() { CHROMIX_NINJA=ninja; }\n'
            'chromix_import_upstream_cache() { return 99; }\n'
            'chromix_build_restored_target() { shift 2; "$CHROMIX_NINJA" -C "$OUT" "$@"; }\n'
            'chromix_report_upstream_plan() { "$CHROMIX_NINJA" -C "$OUT" -n "$@"; }\n')
        self.executable(self.src / "out/Default/gn")
        (self.src / ".chromix-upstream-restored.json").write_text("{}")
        self.object = self.src / "out/Default/obj/keep.o"
        self.object.parent.mkdir()
        self.object.write_text("retained compiler object")
        self.before = self.object.stat().st_mtime_ns
        self.env = {key: value for key, value in os.environ.items()
                    if not key.startswith("DYLD_") and key not in ("BASH_ENV", "ENV")}
        self.env.update(PATH=str(self.bin) + os.pathsep + os.environ["PATH"], CALL_LOG=str(self.log),
                        CHROMIX_APPLY_DOMAIN_SUBSTITUTION="0", CHROMIX_JOBS="1", GITHUB_ACTIONS="false")

    def executable(self, path):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(f"#!{sys.executable}\n" + MOCK_COMMAND)
        path.chmod(0o755)

    def configure(self, arch):
        destination = layout(self.src, arch)
        wrapper = wrapper_fixture(self.src)
        for directory in runtime.LIBRARY_DIRS:
            binary(self.src / directory / "libc++abi.dylib", arch)
        self.env.update(MACHINE="arm64" if arch == "arm64" else "x86_64",
                        DYLD_LIBRARY_PATH="/poisoned", DYLD_INSERT_LIBRARIES="/poisoned",
                        DYLD_UNKNOWN_OVERRIDE="/poisoned", DYLD_FALLBACK_LIBRARY_PATH="/poisoned",
                        BINDGEN_WRAPPER=str(wrapper), WRAPPER_SHA256=runtime.BINDGEN_PATCHED_SHA256,
                        LOADER_LINK=str(destination), LLVM_RUNTIME=str(self.src / runtime.LIBRARY_DIRS[2] / "libLLVM.dylib"))

    def run_script(self, relative, *args):
        return subprocess.run([str(self.SHELL), "-euo", "pipefail", str(self.repo / relative), *args],
                              env=self.env, text=True, capture_output=True, timeout=20)

    def calls(self):
        return [json.loads(line) for line in self.log.read_text().splitlines()]

    def test_scrubs_before_inspect_and_finish_without_rebuilding_bindgen(self):
        self.configure("arm64")
        result = self.run_script("build/posix/prepare-restored-tools.sh", str(self.work), "macos", "arm64")
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        calls = self.calls()
        self.assertEqual(calls[0][1][1:3], ["--phase", "inspect"])
        self.assertEqual(calls[-1][1][1:3], ["--phase", "finish"])
        self.assertTrue(all(env == {} for _, _, env in calls))
        self.assertFalse(any(name == "build_bindgen.py" for name, _, _ in calls))
        self.assertEqual(self.object.stat().st_mtime_ns, self.before)

    def test_bindgen_build_and_finish_receive_clean_environment(self):
        self.configure("x64")
        self.env.update(REBUILD_BINDGEN="1", GITHUB_ACTIONS="true")
        result = self.run_script("build/posix/prepare-restored-tools.sh", str(self.work), "macos", "x64")
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("build_bindgen.py", [name for name, _, _ in self.calls()])
        self.assertTrue(all(env == {} for _, _, env in self.calls()))

    def test_builder_parent_child_gn_and_ninja_stay_clean_for_both_arches(self):
        for arch in runtime.TRIPLES:
            with self.subTest(arch=arch):
                if arch != "arm64":
                    shutil.rmtree(self.src / "third_party")
                    self.log.unlink()
                self.configure(arch)
                result = self.run_script("build/macos/build.sh", str(self.work), arch)
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                calls = self.calls()
                self.assertEqual(calls[0][0], "prepare-ungoogled.sh")
                self.assertIn("prepare_restored_build.py", [name for name, _, _ in calls])
                self.assertEqual([name for name, _, _ in calls[-3:]], ["gn", "ninja", "ninja"])
                self.assertTrue(all(env == {} for _, _, env in calls))
                self.assertEqual(self.object.stat().st_mtime_ns, self.before)

    def test_retrieval_preserves_clean_child_and_parent_environments(self):
        self.configure("x64")
        (self.src / runtime.LIBRARY_DIRS[2] / "libLLVM.dylib").unlink()
        self.env.update(RETRIEVE_RUNTIME="1", REBUILD_BINDGEN="1", GITHUB_ACTIONS="true")
        result = self.run_script("build/macos/build.sh", str(self.work), "x64")
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        calls = self.calls()
        self.assertTrue(all(env == {} for _, _, env in calls))
        self.assertIn("retrieve_and_unpack_resource.py", [name for name, _, _ in calls])
        self.assertIn("build_bindgen.py", [name for name, _, _ in calls])
        self.assertEqual([name for name, _, _ in calls[-3:]], ["gn", "ninja", "ninja"])

    def test_failed_loader_probe_blocks_bindgen_finish_and_ready_marker(self):
        self.configure("arm64")
        self.env.update(FAIL_LOADER_PROBE="1", REBUILD_BINDGEN="1", GITHUB_ACTIONS="true")
        result = self.run_script("build/posix/prepare-restored-tools.sh", str(self.work), "macos", "arm64")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("Rust LLVM loader probe exited -6", result.stderr)
        calls = self.calls()
        self.assertEqual(calls[-1][0], "verify-loader")
        self.assertFalse(any(name == "build_bindgen.py" or "finish" in args for name, args, _ in calls))
        self.assertFalse((self.src / ".chromix-toolchain-ready").exists())
        self.assertEqual(self.object.stat().st_mtime_ns, self.before)

    def test_wrapper_drift_blocks_finish_gn_and_ready_marker(self):
        self.configure("arm64")
        wrapper = Path(self.env["BINDGEN_WRAPPER"])
        drift = wrapper.read_bytes() + b"# unknown change\n"
        wrapper.write_bytes(drift)
        result = self.run_script("build/macos/build.sh", str(self.work), "arm64")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("unknown bindgen wrapper SHA256", result.stderr)
        self.assertEqual(wrapper.read_bytes(), drift)
        self.assertFalse(any(name in ("build_bindgen.py", "gn", "ninja") or "finish" in args
                             for name, args, _ in self.calls()))
        self.assertFalse((self.src / ".chromix-toolchain-ready").exists())
        self.assertEqual(self.object.stat().st_mtime_ns, self.before)

    def test_cli_scrubs_all_inherited_dyld_overrides_in_bash(self):
        self.configure("arm64")
        env = dict(self.env, DYLD_LIBRARY_PATH="/bad", DYLD_INSERT_LIBRARIES="/bad",
                   DYLD_FALLBACK_LIBRARY_PATH="/bad", DYLD_VERSIONED_FRAMEWORK_PATH="/bad")
        command = 'value="$("$1" "$2" --src "$3" --arch arm64)"; eval "$value"; "$1" -c '\
                  "'import json, os; print(json.dumps({k: v for k, v in os.environ.items() if k.startswith(\"DYLD_\")}))'"
        result = subprocess.run([str(self.SHELL), "-euo", "pipefail", "-c", command, "fixture",
                                 sys.executable, str(REPO / "tools/macos_runtime.py"), str(self.src)],
                                env=env, text=True, capture_output=True, timeout=10)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(json.loads(result.stdout), {})

    def test_cli_scrubs_shell_variables_hidden_from_python_by_sip(self):
        self.configure("arm64")
        command = 'DYLD_LIBRARY_PATH=/bad; DYLD_HIDDEN_OVERRIDE=/bad; '
        command += 'value="$(unset -- "${!DYLD_@}"; "$1" "$2" --src "$3" --arch arm64)"; '
        command += 'eval "$value"; test -z "${!DYLD_@}"'
        result = subprocess.run([str(self.SHELL), "-euo", "pipefail", "-c", command, "fixture",
                                 sys.executable, str(REPO / "tools/macos_runtime.py"), str(self.src)],
                                env=self.env, text=True, capture_output=True, timeout=10)
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_wrong_host_fails_before_any_probe_or_loader_write(self):
        self.configure("arm64")
        for relative, args in (("build/macos/build.sh", (str(self.work), "x64")),
                               ("build/posix/prepare-restored-tools.sh", (str(self.work), "macos", "x64"))):
            result = self.run_script(relative, *args)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("native", result.stderr)
            self.assertFalse(self.log.exists())
            self.assertFalse(Path(self.env["LOADER_LINK"]).exists())

    def test_quoted_shell_output_does_not_execute_path_contents(self):
        src = self.root / "$(touch INJECTED) ' runtime"
        src.mkdir()
        layout(src)
        command = 'value="$("$1" "$2" --src "$3" --arch arm64)"; eval "$value"; "$1" -c '\
                  "'import os; print(os.environ.get(\"DYLD_LIBRARY_PATH\", \"clean\"))'"
        result = subprocess.run([str(self.SHELL), "-euo", "pipefail", "-c", command, "fixture",
                                 sys.executable, str(REPO / "tools/macos_runtime.py"), str(src)],
                                cwd=self.root, text=True, capture_output=True, timeout=10)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stdout.strip(), "clean")
        self.assertFalse((self.root / "INJECTED").exists())


@unittest.skipUnless(BASH32.is_file(), "locally built Bash 3.2 required")
class MacOSRuntimeBash32Test(MacOSRuntimeShellTest):
    SHELL = BASH32


if __name__ == "__main__":
    unittest.main()
